package com.lgx.libframe.model;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class Menus {
	public static String AppMenu = "AppMenu";
	public static String WebMenu = "WebMenu";
	public static Map<String, List<MenuObj>> allMenus = new HashMap<String, List<MenuObj>>();
	static {
		List<MenuObj> AppMenu_menuList = new ArrayList<MenuObj>();
		Menus.allMenus.put(AppMenu, AppMenu_menuList);
		MenuObj AppMenu_menu1 = new MenuObj();
		AppMenu_menu1.setMenuId("1");
		AppMenu_menu1.setMenuName("项目预算");
		AppMenu_menu1.setMenuOpName("xmys_app");
		AppMenu_menu1.setAction("");
		AppMenu_menu1.setIcon("");
		AppMenu_menu1.setParentMenuId("0");
		AppMenu_menu1.setChidren(new ArrayList<MenuObj>());
		AppMenu_menuList.add(AppMenu_menu1);
		MenuObj AppMenu_menu1_1 = new MenuObj();
		AppMenu_menu1_1.setMenuId("1,1");
		AppMenu_menu1_1.setMenuName("全局预算");
		AppMenu_menu1_1.setMenuOpName("xmys_qjys_app");
		AppMenu_menu1_1.setAction("com.lgx.price.accounting.budget.global.GlobalBudgetActivity.ACTION");
		AppMenu_menu1_1.setIcon("qjys");
		AppMenu_menu1_1.setParentMenuId("1");
		AppMenu_menu1.getChidren().add(AppMenu_menu1_1);
		MenuObj AppMenu_menu1_1_1 = new MenuObj();
		AppMenu_menu1_1_1.setMenuId("1,1,1");
		AppMenu_menu1_1_1.setMenuName("工程量清单查看价格");
		AppMenu_menu1_1_1.setMenuOpName("xmys_qjys_gclqd_price_app");
		AppMenu_menu1_1_1.setAction("");
		AppMenu_menu1_1_1.setIcon("");
		AppMenu_menu1_1_1.setParentMenuId("1,1");
		AppMenu_menu1_1.getChidren().add(AppMenu_menu1_1_1);
		MenuObj AppMenu_menu1_2 = new MenuObj();
		AppMenu_menu1_2.setMenuId("1,2");
		AppMenu_menu1_2.setMenuName("目标预算");
		AppMenu_menu1_2.setMenuOpName("xmys_mbys_app");
		AppMenu_menu1_2.setAction("com.lgx.price.accounting.budget.purpose.PurposeBudgetActivity.ACTION");
		AppMenu_menu1_2.setIcon("mbys");
		AppMenu_menu1_2.setParentMenuId("1");
		AppMenu_menu1.getChidren().add(AppMenu_menu1_2);
		MenuObj AppMenu_menu2 = new MenuObj();
		AppMenu_menu2.setMenuId("2");
		AppMenu_menu2.setMenuName("统计");
		AppMenu_menu2.setMenuOpName("tj_app");
		AppMenu_menu2.setAction("");
		AppMenu_menu2.setIcon("");
		AppMenu_menu2.setParentMenuId("0");
		AppMenu_menu2.setChidren(new ArrayList<MenuObj>());
		AppMenu_menuList.add(AppMenu_menu2);
		MenuObj AppMenu_menu2_1 = new MenuObj();
		AppMenu_menu2_1.setMenuId("2,1");
		AppMenu_menu2_1.setMenuName("成本统计");
		AppMenu_menu2_1.setMenuOpName("tj_cbtj_app");
		AppMenu_menu2_1.setAction("com.lgx.price.accounting.statistics.cost.CostActivity.ACTION");
		AppMenu_menu2_1.setIcon("cbtj");
		AppMenu_menu2_1.setParentMenuId("2");
		AppMenu_menu2.getChidren().add(AppMenu_menu2_1);
		MenuObj AppMenu_menu2_1_1 = new MenuObj();
		AppMenu_menu2_1_1.setMenuId("2,1,1");
		AppMenu_menu2_1_1.setMenuName("间接成本");
		AppMenu_menu2_1_1.setMenuOpName("tj_cbtj_jjcb_app");
		AppMenu_menu2_1_1.setAction("");
		AppMenu_menu2_1_1.setIcon("");
		AppMenu_menu2_1_1.setParentMenuId("2,1");
		AppMenu_menu2_1.getChidren().add(AppMenu_menu2_1_1);
		MenuObj AppMenu_menu2_1_1_1 = new MenuObj();
		AppMenu_menu2_1_1_1.setMenuId("2,1,1,1");
		AppMenu_menu2_1_1_1.setMenuName("间接成本");
		AppMenu_menu2_1_1_1.setMenuOpName("tj_cbtj_jjcb_jjcb_app");
		AppMenu_menu2_1_1_1.setAction("");
		AppMenu_menu2_1_1_1.setIcon("");
		AppMenu_menu2_1_1_1.setParentMenuId("2,1,1");
		AppMenu_menu2_1_1.getChidren().add(AppMenu_menu2_1_1_1);
		MenuObj AppMenu_menu2_1_2 = new MenuObj();
		AppMenu_menu2_1_2.setMenuId("2,1,2");
		AppMenu_menu2_1_2.setMenuName("直接成本");
		AppMenu_menu2_1_2.setMenuOpName("tj_cbtj_zjcb_app");
		AppMenu_menu2_1_2.setAction("");
		AppMenu_menu2_1_2.setIcon("");
		AppMenu_menu2_1_2.setParentMenuId("2,1");
		AppMenu_menu2_1.getChidren().add(AppMenu_menu2_1_2);
		MenuObj AppMenu_menu2_1_2_1 = new MenuObj();
		AppMenu_menu2_1_2_1.setMenuId("2,1,2,1");
		AppMenu_menu2_1_2_1.setMenuName("材料成本");
		AppMenu_menu2_1_2_1.setMenuOpName("tj_cbtj_zjcb_clcb_app");
		AppMenu_menu2_1_2_1.setAction("");
		AppMenu_menu2_1_2_1.setIcon("");
		AppMenu_menu2_1_2_1.setParentMenuId("2,1,2");
		AppMenu_menu2_1_2.getChidren().add(AppMenu_menu2_1_2_1);
		MenuObj AppMenu_menu2_1_2_2 = new MenuObj();
		AppMenu_menu2_1_2_2.setMenuId("2,1,2,2");
		AppMenu_menu2_1_2_2.setMenuName("分包成本");
		AppMenu_menu2_1_2_2.setMenuOpName("tj_cbtj_zjcb_fbcb_app");
		AppMenu_menu2_1_2_2.setAction("");
		AppMenu_menu2_1_2_2.setIcon("");
		AppMenu_menu2_1_2_2.setParentMenuId("2,1,2");
		AppMenu_menu2_1_2.getChidren().add(AppMenu_menu2_1_2_2);
		MenuObj AppMenu_menu2_1_2_2_1 = new MenuObj();
		AppMenu_menu2_1_2_2_1.setMenuId("2,1,2,2,1");
		AppMenu_menu2_1_2_2_1.setMenuName("分包工程量统计");
		AppMenu_menu2_1_2_2_1.setMenuOpName("tj_cbtj_zjcb_fbcb_fbgcltj_app");
		AppMenu_menu2_1_2_2_1.setAction("");
		AppMenu_menu2_1_2_2_1.setIcon("");
		AppMenu_menu2_1_2_2_1.setParentMenuId("2,1,2,2");
		AppMenu_menu2_1_2_2.getChidren().add(AppMenu_menu2_1_2_2_1);
		MenuObj AppMenu_menu2_1_2_2_2 = new MenuObj();
		AppMenu_menu2_1_2_2_2.setMenuId("2,1,2,2,2");
		AppMenu_menu2_1_2_2_2.setMenuName("分包价格统计");
		AppMenu_menu2_1_2_2_2.setMenuOpName("tj_cbtj_zjcb_fbcb_fbjgtj_app");
		AppMenu_menu2_1_2_2_2.setAction("");
		AppMenu_menu2_1_2_2_2.setIcon("");
		AppMenu_menu2_1_2_2_2.setParentMenuId("2,1,2,2");
		AppMenu_menu2_1_2_2.getChidren().add(AppMenu_menu2_1_2_2_2);
		MenuObj AppMenu_menu2_1_2_2_3 = new MenuObj();
		AppMenu_menu2_1_2_2_3.setMenuId("2,1,2,2,3");
		AppMenu_menu2_1_2_2_3.setMenuName("临建项目量统计");
		AppMenu_menu2_1_2_2_3.setMenuOpName("tj_cbtj_zjcb_fbcb_ljxmcb_app");
		AppMenu_menu2_1_2_2_3.setAction("");
		AppMenu_menu2_1_2_2_3.setIcon("");
		AppMenu_menu2_1_2_2_3.setParentMenuId("2,1,2,2");
		AppMenu_menu2_1_2_2.getChidren().add(AppMenu_menu2_1_2_2_3);
		MenuObj AppMenu_menu2_1_2_2_4 = new MenuObj();
		AppMenu_menu2_1_2_2_4.setMenuId("2,1,2,2,4");
		AppMenu_menu2_1_2_2_4.setMenuName("临建项目价格统计");
		AppMenu_menu2_1_2_2_4.setMenuOpName("tj_cbtj_zjcb_fbcb_ljxmjg_app");
		AppMenu_menu2_1_2_2_4.setAction("");
		AppMenu_menu2_1_2_2_4.setIcon("");
		AppMenu_menu2_1_2_2_4.setParentMenuId("2,1,2,2");
		AppMenu_menu2_1_2_2.getChidren().add(AppMenu_menu2_1_2_2_4);
		MenuObj AppMenu_menu2_1_2_3 = new MenuObj();
		AppMenu_menu2_1_2_3.setMenuId("2,1,2,3");
		AppMenu_menu2_1_2_3.setMenuName("机械成本");
		AppMenu_menu2_1_2_3.setMenuOpName("tj_cbtj_zjcb_jxcb_app");
		AppMenu_menu2_1_2_3.setAction("");
		AppMenu_menu2_1_2_3.setIcon("");
		AppMenu_menu2_1_2_3.setParentMenuId("2,1,2");
		AppMenu_menu2_1_2.getChidren().add(AppMenu_menu2_1_2_3);
		MenuObj AppMenu_menu2_1_2_4 = new MenuObj();
		AppMenu_menu2_1_2_4.setMenuId("2,1,2,4");
		AppMenu_menu2_1_2_4.setMenuName("零星用工");
		AppMenu_menu2_1_2_4.setMenuOpName("tj_cbtj_zjcb_lxyg_app");
		AppMenu_menu2_1_2_4.setAction("");
		AppMenu_menu2_1_2_4.setIcon("");
		AppMenu_menu2_1_2_4.setParentMenuId("2,1,2");
		AppMenu_menu2_1_2.getChidren().add(AppMenu_menu2_1_2_4);
		MenuObj AppMenu_menu2_1_2_5 = new MenuObj();
		AppMenu_menu2_1_2_5.setMenuId("2,1,2,5");
		AppMenu_menu2_1_2_5.setMenuName("其他直接成本");
		AppMenu_menu2_1_2_5.setMenuOpName("tj_cbtj_zjcb_qtzjcb_app");
		AppMenu_menu2_1_2_5.setAction("");
		AppMenu_menu2_1_2_5.setIcon("");
		AppMenu_menu2_1_2_5.setParentMenuId("2,1,2");
		AppMenu_menu2_1_2.getChidren().add(AppMenu_menu2_1_2_5);
		MenuObj AppMenu_menu2_1_3 = new MenuObj();
		AppMenu_menu2_1_3.setMenuId("2,1,3");
		AppMenu_menu2_1_3.setMenuName("管理费用");
		AppMenu_menu2_1_3.setMenuOpName("tj_cbtj_glfy_app");
		AppMenu_menu2_1_3.setAction("");
		AppMenu_menu2_1_3.setIcon("");
		AppMenu_menu2_1_3.setParentMenuId("2,1");
		AppMenu_menu2_1.getChidren().add(AppMenu_menu2_1_3);
		MenuObj AppMenu_menu2_1_3_1 = new MenuObj();
		AppMenu_menu2_1_3_1.setMenuId("2,1,3,1");
		AppMenu_menu2_1_3_1.setMenuName("管理费用");
		AppMenu_menu2_1_3_1.setMenuOpName("tj_cbtj_glfy_glfy_app");
		AppMenu_menu2_1_3_1.setAction("");
		AppMenu_menu2_1_3_1.setIcon("");
		AppMenu_menu2_1_3_1.setParentMenuId("2,1,3");
		AppMenu_menu2_1_3.getChidren().add(AppMenu_menu2_1_3_1);
		MenuObj AppMenu_menu2_2 = new MenuObj();
		AppMenu_menu2_2.setMenuId("2,2");
		AppMenu_menu2_2.setMenuName("收入统计");
		AppMenu_menu2_2.setMenuOpName("tj_srtj_app");
		AppMenu_menu2_2.setAction("com.lgx.price.accounting.statistics.income.IncomeActivity.ACTION");
		AppMenu_menu2_2.setIcon("srtj");
		AppMenu_menu2_2.setParentMenuId("2");
		AppMenu_menu2.getChidren().add(AppMenu_menu2_2);
		MenuObj AppMenu_menu2_2_1 = new MenuObj();
		AppMenu_menu2_2_1.setMenuId("2,2,1");
		AppMenu_menu2_2_1.setMenuName("收入统计");
		AppMenu_menu2_2_1.setMenuOpName("tj_srtj_srtj_app");
		AppMenu_menu2_2_1.setAction("");
		AppMenu_menu2_2_1.setIcon("");
		AppMenu_menu2_2_1.setParentMenuId("2,2");
		AppMenu_menu2_2.getChidren().add(AppMenu_menu2_2_1);
		MenuObj AppMenu_menu2_2_2 = new MenuObj();
		AppMenu_menu2_2_2.setMenuId("2,2,2");
		AppMenu_menu2_2_2.setMenuName("新增收入量统计");
		AppMenu_menu2_2_2.setMenuOpName("tj_srtj_xzsrtj_app");
		AppMenu_menu2_2_2.setAction("");
		AppMenu_menu2_2_2.setIcon("");
		AppMenu_menu2_2_2.setParentMenuId("2,2");
		AppMenu_menu2_2.getChidren().add(AppMenu_menu2_2_2);
		MenuObj AppMenu_menu2_2_3 = new MenuObj();
		AppMenu_menu2_2_3.setMenuId("2,2,3");
		AppMenu_menu2_2_3.setMenuName("新增收入价格统计");
		AppMenu_menu2_2_3.setMenuOpName("tj_srtj_xzsrjg_app");
		AppMenu_menu2_2_3.setAction("");
		AppMenu_menu2_2_3.setIcon("");
		AppMenu_menu2_2_3.setParentMenuId("2,2");
		AppMenu_menu2_2.getChidren().add(AppMenu_menu2_2_3);
		MenuObj AppMenu_menu2_3 = new MenuObj();
		AppMenu_menu2_3.setMenuId("2,3");
		AppMenu_menu2_3.setMenuName("资源统计");
		AppMenu_menu2_3.setMenuOpName("tj_zytj_app");
		AppMenu_menu2_3.setAction("com.lgx.price.accounting.statistics.resources.ResourcesActivity.ACTION");
		AppMenu_menu2_3.setIcon("zytj");
		AppMenu_menu2_3.setParentMenuId("2");
		AppMenu_menu2.getChidren().add(AppMenu_menu2_3);
		MenuObj AppMenu_menu2_3_1 = new MenuObj();
		AppMenu_menu2_3_1.setMenuId("2,3,1");
		AppMenu_menu2_3_1.setMenuName("分包商成本");
		AppMenu_menu2_3_1.setMenuOpName("tj_zytj_fbscb_app");
		AppMenu_menu2_3_1.setAction("");
		AppMenu_menu2_3_1.setIcon("");
		AppMenu_menu2_3_1.setParentMenuId("2,3");
		AppMenu_menu2_3.getChidren().add(AppMenu_menu2_3_1);
		MenuObj AppMenu_menu2_3_2 = new MenuObj();
		AppMenu_menu2_3_2.setMenuId("2,3,2");
		AppMenu_menu2_3_2.setMenuName("重点工序核算");
		AppMenu_menu2_3_2.setMenuOpName("tj_zytj_zdgxhs_app");
		AppMenu_menu2_3_2.setAction("");
		AppMenu_menu2_3_2.setIcon("");
		AppMenu_menu2_3_2.setParentMenuId("2,3");
		AppMenu_menu2_3.getChidren().add(AppMenu_menu2_3_2);
		MenuObj AppMenu_menu3 = new MenuObj();
		AppMenu_menu3.setMenuId("3");
		AppMenu_menu3.setMenuName("数据分析");
		AppMenu_menu3.setMenuOpName("sjfx_app");
		AppMenu_menu3.setAction("");
		AppMenu_menu3.setIcon("");
		AppMenu_menu3.setParentMenuId("0");
		AppMenu_menu3.setChidren(new ArrayList<MenuObj>());
		AppMenu_menuList.add(AppMenu_menu3);
		MenuObj AppMenu_menu3_1 = new MenuObj();
		AppMenu_menu3_1.setMenuId("3,1");
		AppMenu_menu3_1.setMenuName("成本收入报表");
		AppMenu_menu3_1.setMenuOpName("sjfx_cbsrbb_app");
		AppMenu_menu3_1.setAction("com.lgx.price.accounting.analysis.costincome.CostIncomeReportActivity.ACTION");
		AppMenu_menu3_1.setIcon("cbsrbb");
		AppMenu_menu3_1.setParentMenuId("3");
		AppMenu_menu3.getChidren().add(AppMenu_menu3_1);
		MenuObj AppMenu_menu3_2 = new MenuObj();
		AppMenu_menu3_2.setMenuId("3,2");
		AppMenu_menu3_2.setMenuName("资源报表");
		AppMenu_menu3_2.setMenuOpName("sjfx_zybb_app");
		AppMenu_menu3_2.setAction("com.lgx.price.accounting.analysis.resources.ResourcesReportActivity.ACTION");
		AppMenu_menu3_2.setIcon("zybb");
		AppMenu_menu3_2.setParentMenuId("3");
		AppMenu_menu3.getChidren().add(AppMenu_menu3_2);
		MenuObj AppMenu_menu3_3 = new MenuObj();
		AppMenu_menu3_3.setMenuId("3,3");
		AppMenu_menu3_3.setMenuName("查询");
		AppMenu_menu3_3.setMenuOpName("cx_app");
		AppMenu_menu3_3.setAction("com.lgx.price.accounting.analysis.search.SearchActivity.ACTION");
		AppMenu_menu3_3.setIcon("cx");
		AppMenu_menu3_3.setParentMenuId("3");
		AppMenu_menu3.getChidren().add(AppMenu_menu3_3);
		MenuObj AppMenu_menu3_4 = new MenuObj();
		AppMenu_menu3_4.setMenuId("3,4");
		AppMenu_menu3_4.setMenuName("材料核销");
		AppMenu_menu3_4.setMenuOpName("clhx_app");
		AppMenu_menu3_4.setAction("com.lgx.price.accounting.analysis.clhx.ClhxActivity.ACTION");
		AppMenu_menu3_4.setIcon("clhx");
		AppMenu_menu3_4.setParentMenuId("3");
		AppMenu_menu3.getChidren().add(AppMenu_menu3_4);
		MenuObj AppMenu_menu3_4_1 = new MenuObj();
		AppMenu_menu3_4_1.setMenuId("3,4,1");
		AppMenu_menu3_4_1.setMenuName("自营材料核销");
		AppMenu_menu3_4_1.setMenuOpName("clhx_zyclhx_app");
		AppMenu_menu3_4_1.setAction("");
		AppMenu_menu3_4_1.setIcon("");
		AppMenu_menu3_4_1.setParentMenuId("3,4");
		AppMenu_menu3_4.getChidren().add(AppMenu_menu3_4_1);
		MenuObj AppMenu_menu3_4_2 = new MenuObj();
		AppMenu_menu3_4_2.setMenuId("3,4,2");
		AppMenu_menu3_4_2.setMenuName("分包材料核销");
		AppMenu_menu3_4_2.setMenuOpName("clhx_hbclhx_app");
		AppMenu_menu3_4_2.setAction("");
		AppMenu_menu3_4_2.setIcon("");
		AppMenu_menu3_4_2.setParentMenuId("3,4");
		AppMenu_menu3_4.getChidren().add(AppMenu_menu3_4_2);
		MenuObj AppMenu_menu3_5 = new MenuObj();
		AppMenu_menu3_5.setMenuId("3,5");
		AppMenu_menu3_5.setMenuName("成本分析");
		AppMenu_menu3_5.setMenuOpName("cbfx_app");
		AppMenu_menu3_5.setAction("com.lgx.price.accounting.analysis.cbfx.CbfxActivity.ACTION");
		AppMenu_menu3_5.setIcon("cbfx");
		AppMenu_menu3_5.setParentMenuId("3");
		AppMenu_menu3.getChidren().add(AppMenu_menu3_5);
		MenuObj AppMenu_menu4 = new MenuObj();
		AppMenu_menu4.setMenuId("4");
		AppMenu_menu4.setMenuName("财务");
		AppMenu_menu4.setMenuOpName("cw_app");
		AppMenu_menu4.setAction("");
		AppMenu_menu4.setIcon("");
		AppMenu_menu4.setParentMenuId("0");
		AppMenu_menu4.setChidren(new ArrayList<MenuObj>());
		AppMenu_menuList.add(AppMenu_menu4);
		MenuObj AppMenu_menu4_1 = new MenuObj();
		AppMenu_menu4_1.setMenuId("4,1");
		AppMenu_menu4_1.setMenuName("费用报销");
		AppMenu_menu4_1.setMenuOpName("cw_fybx_app");
		AppMenu_menu4_1.setAction("com.lgx.price.accounting.finance.fybx.FybxActivity.ACTION");
		AppMenu_menu4_1.setIcon("fybx");
		AppMenu_menu4_1.setParentMenuId("4");
		AppMenu_menu4.getChidren().add(AppMenu_menu4_1);
		MenuObj AppMenu_menu4_2 = new MenuObj();
		AppMenu_menu4_2.setMenuId("4,2");
		AppMenu_menu4_2.setMenuName("报销记录");
		AppMenu_menu4_2.setMenuOpName("cw_bxjl_app");
		AppMenu_menu4_2.setAction("com.lgx.price.accounting.finance.bxjl.BxjlActivity.ACTION");
		AppMenu_menu4_2.setIcon("bxjl");
		AppMenu_menu4_2.setParentMenuId("4");
		AppMenu_menu4.getChidren().add(AppMenu_menu4_2);
		MenuObj AppMenu_menu4_2_1 = new MenuObj();
		AppMenu_menu4_2_1.setMenuId("4,2,1");
		AppMenu_menu4_2_1.setMenuName("财务审核");
		AppMenu_menu4_2_1.setMenuOpName("cw_sh_app");
		AppMenu_menu4_2_1.setAction("");
		AppMenu_menu4_2_1.setIcon("");
		AppMenu_menu4_2_1.setParentMenuId("4,2");
		AppMenu_menu4_2.getChidren().add(AppMenu_menu4_2_1);
		MenuObj AppMenu_menu4_3 = new MenuObj();
		AppMenu_menu4_3.setMenuId("4,3");
		AppMenu_menu4_3.setMenuName("对上结算");
		AppMenu_menu4_3.setMenuOpName("cw_dsjs_app");
		AppMenu_menu4_3.setAction("com.lgx.price.accounting.finance.dsjs.DsjsActivity.ACTION");
		AppMenu_menu4_3.setIcon("dsjs");
		AppMenu_menu4_3.setParentMenuId("4");
		AppMenu_menu4.getChidren().add(AppMenu_menu4_3);
		MenuObj AppMenu_menu4_4 = new MenuObj();
		AppMenu_menu4_4.setMenuId("4,4");
		AppMenu_menu4_4.setMenuName("对下结算");
		AppMenu_menu4_4.setMenuOpName("cw_dxjs_app");
		AppMenu_menu4_4.setAction("com.lgx.price.accounting.finance.dxjs.DxjsActivity.ACTION");
		AppMenu_menu4_4.setIcon("dxjs");
		AppMenu_menu4_4.setParentMenuId("4");
		AppMenu_menu4.getChidren().add(AppMenu_menu4_4);
		List<MenuObj> WebMenu_menuList = new ArrayList<MenuObj>();
		Menus.allMenus.put(WebMenu, WebMenu_menuList);
		MenuObj WebMenu_menu1 = new MenuObj();
		WebMenu_menu1.setMenuId("1");
		WebMenu_menu1.setMenuName("项目预算");
		WebMenu_menu1.setMenuOpName("xmys_web");
		WebMenu_menu1.setAction("");
		WebMenu_menu1.setIcon("top1");
		WebMenu_menu1.setParentMenuId("0");
		WebMenu_menu1.setChidren(new ArrayList<MenuObj>());
		WebMenu_menuList.add(WebMenu_menu1);
		MenuObj WebMenu_menu1_1 = new MenuObj();
		WebMenu_menu1_1.setMenuId("1,1");
		WebMenu_menu1_1.setMenuName("全局预算");
		WebMenu_menu1_1.setMenuOpName("qjys_web");
		WebMenu_menu1_1.setAction("");
		WebMenu_menu1_1.setIcon("top2");
		WebMenu_menu1_1.setParentMenuId("1");
		WebMenu_menu1.getChidren().add(WebMenu_menu1_1);
		MenuObj WebMenu_menu1_1_1 = new MenuObj();
		WebMenu_menu1_1_1.setMenuId("1,1,1");
		WebMenu_menu1_1_1.setMenuName("总工程量");
		WebMenu_menu1_1_1.setMenuOpName("zgcl_web");
		WebMenu_menu1_1_1.setAction("");
		WebMenu_menu1_1_1.setIcon("left1");
		WebMenu_menu1_1_1.setParentMenuId("1,1");
		WebMenu_menu1_1.getChidren().add(WebMenu_menu1_1_1);
		MenuObj WebMenu_menu1_1_1_1 = new MenuObj();
		WebMenu_menu1_1_1_1.setMenuId("1,1,1,1");
		WebMenu_menu1_1_1_1.setMenuName("总工程量列表");
		WebMenu_menu1_1_1_1.setMenuOpName("zgcllb_web");
		WebMenu_menu1_1_1_1.setAction("../account/overall/projectList.html");
		WebMenu_menu1_1_1_1.setIcon("left2");
		WebMenu_menu1_1_1_1.setParentMenuId("1,1,1");
		WebMenu_menu1_1_1.getChidren().add(WebMenu_menu1_1_1_1);
		MenuObj WebMenu_menu1_1_1_1_1 = new MenuObj();
		WebMenu_menu1_1_1_1_1.setMenuId("1,1,1,1,1");
		WebMenu_menu1_1_1_1_1.setMenuName("查看金额");
		WebMenu_menu1_1_1_1_1.setMenuOpName("zgcllb_web_price");
		WebMenu_menu1_1_1_1_1.setAction("");
		WebMenu_menu1_1_1_1_1.setIcon("");
		WebMenu_menu1_1_1_1_1.setParentMenuId("1,1,1,1");
		WebMenu_menu1_1_1_1.getChidren().add(WebMenu_menu1_1_1_1_1);
		MenuObj WebMenu_menu1_1_1_2 = new MenuObj();
		WebMenu_menu1_1_1_2.setMenuId("1,1,1,2");
		WebMenu_menu1_1_1_2.setMenuName("总工程量导入");
		WebMenu_menu1_1_1_2.setMenuOpName("zgcldr_web");
		WebMenu_menu1_1_1_2.setAction("../account/overall/projectImport.html");
		WebMenu_menu1_1_1_2.setIcon("left2");
		WebMenu_menu1_1_1_2.setParentMenuId("1,1,1");
		WebMenu_menu1_1_1.getChidren().add(WebMenu_menu1_1_1_2);
		MenuObj WebMenu_menu1_1_2 = new MenuObj();
		WebMenu_menu1_1_2.setMenuId("1,1,2");
		WebMenu_menu1_1_2.setMenuName("人、材、机总耗量");
		WebMenu_menu1_1_2.setMenuOpName("rcj_web");
		WebMenu_menu1_1_2.setAction("");
		WebMenu_menu1_1_2.setIcon("left1");
		WebMenu_menu1_1_2.setParentMenuId("1,1");
		WebMenu_menu1_1.getChidren().add(WebMenu_menu1_1_2);
		MenuObj WebMenu_menu1_1_2_1 = new MenuObj();
		WebMenu_menu1_1_2_1.setMenuId("1,1,2,1");
		WebMenu_menu1_1_2_1.setMenuName("人、材、机总耗量列表");
		WebMenu_menu1_1_2_1.setMenuOpName("rcjlb_web");
		WebMenu_menu1_1_2_1.setAction("../account/overall/materialList.html");
		WebMenu_menu1_1_2_1.setIcon("left2");
		WebMenu_menu1_1_2_1.setParentMenuId("1,1,2");
		WebMenu_menu1_1_2.getChidren().add(WebMenu_menu1_1_2_1);
		MenuObj WebMenu_menu1_1_2_2 = new MenuObj();
		WebMenu_menu1_1_2_2.setMenuId("1,1,2,2");
		WebMenu_menu1_1_2_2.setMenuName("人、材、机总耗量导入");
		WebMenu_menu1_1_2_2.setMenuOpName("rcjdr_web");
		WebMenu_menu1_1_2_2.setAction("../account/overall/materialImport.html");
		WebMenu_menu1_1_2_2.setIcon("left2");
		WebMenu_menu1_1_2_2.setParentMenuId("1,1,2");
		WebMenu_menu1_1_2.getChidren().add(WebMenu_menu1_1_2_2);
		MenuObj WebMenu_menu1_1_3 = new MenuObj();
		WebMenu_menu1_1_3.setMenuId("1,1,3");
		WebMenu_menu1_1_3.setMenuName("费用汇总");
		WebMenu_menu1_1_3.setMenuOpName("fyhz_web");
		WebMenu_menu1_1_3.setAction("");
		WebMenu_menu1_1_3.setIcon("left1");
		WebMenu_menu1_1_3.setParentMenuId("1,1");
		WebMenu_menu1_1.getChidren().add(WebMenu_menu1_1_3);
		MenuObj WebMenu_menu1_1_3_1 = new MenuObj();
		WebMenu_menu1_1_3_1.setMenuId("1,1,3,1");
		WebMenu_menu1_1_3_1.setMenuName("费用汇总列表");
		WebMenu_menu1_1_3_1.setMenuOpName("fyhzlb_web");
		WebMenu_menu1_1_3_1.setAction("../account/overall/expenseList.html");
		WebMenu_menu1_1_3_1.setIcon("left2");
		WebMenu_menu1_1_3_1.setParentMenuId("1,1,3");
		WebMenu_menu1_1_3.getChidren().add(WebMenu_menu1_1_3_1);
		MenuObj WebMenu_menu1_1_3_2 = new MenuObj();
		WebMenu_menu1_1_3_2.setMenuId("1,1,3,2");
		WebMenu_menu1_1_3_2.setMenuName("费用汇总导入");
		WebMenu_menu1_1_3_2.setMenuOpName("fyhzdr_web");
		WebMenu_menu1_1_3_2.setAction("../account/overall/expenseImport.html");
		WebMenu_menu1_1_3_2.setIcon("left2");
		WebMenu_menu1_1_3_2.setParentMenuId("1,1,3");
		WebMenu_menu1_1_3.getChidren().add(WebMenu_menu1_1_3_2);
		MenuObj WebMenu_menu1_2 = new MenuObj();
		WebMenu_menu1_2.setMenuId("1,2");
		WebMenu_menu1_2.setMenuName("目标预算");
		WebMenu_menu1_2.setMenuOpName("mbys_web");
		WebMenu_menu1_2.setAction("");
		WebMenu_menu1_2.setIcon("top2");
		WebMenu_menu1_2.setParentMenuId("1");
		WebMenu_menu1.getChidren().add(WebMenu_menu1_2);
		MenuObj WebMenu_menu1_2_1 = new MenuObj();
		WebMenu_menu1_2_1.setMenuId("1,2,1");
		WebMenu_menu1_2_1.setMenuName("间接成本");
		WebMenu_menu1_2_1.setMenuOpName("jjcb_web");
		WebMenu_menu1_2_1.setAction("");
		WebMenu_menu1_2_1.setIcon("top3");
		WebMenu_menu1_2_1.setParentMenuId("1,2");
		WebMenu_menu1_2.getChidren().add(WebMenu_menu1_2_1);
		MenuObj WebMenu_menu1_2_1_1 = new MenuObj();
		WebMenu_menu1_2_1_1.setMenuId("1,2,1,1");
		WebMenu_menu1_2_1_1.setMenuName("间接成本列表");
		WebMenu_menu1_2_1_1.setMenuOpName("jjcblb_web");
		WebMenu_menu1_2_1_1.setAction("../account/goal/indirectCostList.html");
		WebMenu_menu1_2_1_1.setIcon("left1");
		WebMenu_menu1_2_1_1.setParentMenuId("1,2,1");
		WebMenu_menu1_2_1.getChidren().add(WebMenu_menu1_2_1_1);
		MenuObj WebMenu_menu1_2_1_1_1 = new MenuObj();
		WebMenu_menu1_2_1_1_1.setMenuId("1,2,1,1,1");
		WebMenu_menu1_2_1_1_1.setMenuName("编辑");
		WebMenu_menu1_2_1_1_1.setMenuOpName("jjcblb_web_ed");
		WebMenu_menu1_2_1_1_1.setAction("");
		WebMenu_menu1_2_1_1_1.setIcon("");
		WebMenu_menu1_2_1_1_1.setParentMenuId("1,2,1,1");
		WebMenu_menu1_2_1_1.getChidren().add(WebMenu_menu1_2_1_1_1);
		MenuObj WebMenu_menu1_2_1_1_2 = new MenuObj();
		WebMenu_menu1_2_1_1_2.setMenuId("1,2,1,1,2");
		WebMenu_menu1_2_1_1_2.setMenuName("删除");
		WebMenu_menu1_2_1_1_2.setMenuOpName("jjcblb_web_del");
		WebMenu_menu1_2_1_1_2.setAction("");
		WebMenu_menu1_2_1_1_2.setIcon("");
		WebMenu_menu1_2_1_1_2.setParentMenuId("1,2,1,1");
		WebMenu_menu1_2_1_1.getChidren().add(WebMenu_menu1_2_1_1_2);
		MenuObj WebMenu_menu1_2_2 = new MenuObj();
		WebMenu_menu1_2_2.setMenuId("1,2,2");
		WebMenu_menu1_2_2.setMenuName("直接成本");
		WebMenu_menu1_2_2.setMenuOpName("zjcb_web");
		WebMenu_menu1_2_2.setAction("");
		WebMenu_menu1_2_2.setIcon("top3");
		WebMenu_menu1_2_2.setParentMenuId("1,2");
		WebMenu_menu1_2.getChidren().add(WebMenu_menu1_2_2);
		MenuObj WebMenu_menu1_2_2_1 = new MenuObj();
		WebMenu_menu1_2_2_1.setMenuId("1,2,2,1");
		WebMenu_menu1_2_2_1.setMenuName("自营预算");
		WebMenu_menu1_2_2_1.setMenuOpName("zyys_web");
		WebMenu_menu1_2_2_1.setAction("");
		WebMenu_menu1_2_2_1.setIcon("left1");
		WebMenu_menu1_2_2_1.setParentMenuId("1,2,2");
		WebMenu_menu1_2_2.getChidren().add(WebMenu_menu1_2_2_1);
		MenuObj WebMenu_menu1_2_2_1_1 = new MenuObj();
		WebMenu_menu1_2_2_1_1.setMenuId("1,2,2,1,1");
		WebMenu_menu1_2_2_1_1.setMenuName("自营预算材料成本");
		WebMenu_menu1_2_2_1_1.setMenuOpName("zycl_web");
		WebMenu_menu1_2_2_1_1.setAction("../account/goal/materialCostList_self.html");
		WebMenu_menu1_2_2_1_1.setIcon("left2");
		WebMenu_menu1_2_2_1_1.setParentMenuId("1,2,2,1");
		WebMenu_menu1_2_2_1.getChidren().add(WebMenu_menu1_2_2_1_1);
		MenuObj WebMenu_menu1_2_2_1_1_1 = new MenuObj();
		WebMenu_menu1_2_2_1_1_1.setMenuId("1,2,2,1,1,1");
		WebMenu_menu1_2_2_1_1_1.setMenuName("编辑");
		WebMenu_menu1_2_2_1_1_1.setMenuOpName("zycl_web_ed");
		WebMenu_menu1_2_2_1_1_1.setAction("");
		WebMenu_menu1_2_2_1_1_1.setIcon("");
		WebMenu_menu1_2_2_1_1_1.setParentMenuId("1,2,2,1,1");
		WebMenu_menu1_2_2_1_1.getChidren().add(WebMenu_menu1_2_2_1_1_1);
		MenuObj WebMenu_menu1_2_2_1_1_2 = new MenuObj();
		WebMenu_menu1_2_2_1_1_2.setMenuId("1,2,2,1,1,2");
		WebMenu_menu1_2_2_1_1_2.setMenuName("删除");
		WebMenu_menu1_2_2_1_1_2.setMenuOpName("zycl_web_del");
		WebMenu_menu1_2_2_1_1_2.setAction("");
		WebMenu_menu1_2_2_1_1_2.setIcon("");
		WebMenu_menu1_2_2_1_1_2.setParentMenuId("1,2,2,1,1");
		WebMenu_menu1_2_2_1_1.getChidren().add(WebMenu_menu1_2_2_1_1_2);
		MenuObj WebMenu_menu1_2_2_1_2 = new MenuObj();
		WebMenu_menu1_2_2_1_2.setMenuId("1,2,2,1,2");
		WebMenu_menu1_2_2_1_2.setMenuName("自营预算零星用工");
		WebMenu_menu1_2_2_1_2.setMenuOpName("zylxyg_web");
		WebMenu_menu1_2_2_1_2.setAction("../account/goal/workerCostList.html");
		WebMenu_menu1_2_2_1_2.setIcon("left2");
		WebMenu_menu1_2_2_1_2.setParentMenuId("1,2,2,1");
		WebMenu_menu1_2_2_1.getChidren().add(WebMenu_menu1_2_2_1_2);
		MenuObj WebMenu_menu1_2_2_1_2_1 = new MenuObj();
		WebMenu_menu1_2_2_1_2_1.setMenuId("1,2,2,1,2,1");
		WebMenu_menu1_2_2_1_2_1.setMenuName("编辑");
		WebMenu_menu1_2_2_1_2_1.setMenuOpName("zylxyg_web_ed");
		WebMenu_menu1_2_2_1_2_1.setAction("");
		WebMenu_menu1_2_2_1_2_1.setIcon("");
		WebMenu_menu1_2_2_1_2_1.setParentMenuId("1,2,2,1,2");
		WebMenu_menu1_2_2_1_2.getChidren().add(WebMenu_menu1_2_2_1_2_1);
		MenuObj WebMenu_menu1_2_2_1_2_2 = new MenuObj();
		WebMenu_menu1_2_2_1_2_2.setMenuId("1,2,2,1,2,2");
		WebMenu_menu1_2_2_1_2_2.setMenuName("删除");
		WebMenu_menu1_2_2_1_2_2.setMenuOpName("zylxyg_web_del");
		WebMenu_menu1_2_2_1_2_2.setAction("");
		WebMenu_menu1_2_2_1_2_2.setIcon("");
		WebMenu_menu1_2_2_1_2_2.setParentMenuId("1,2,2,1,2");
		WebMenu_menu1_2_2_1_2.getChidren().add(WebMenu_menu1_2_2_1_2_2);
		MenuObj WebMenu_menu1_2_2_1_3 = new MenuObj();
		WebMenu_menu1_2_2_1_3.setMenuId("1,2,2,1,3");
		WebMenu_menu1_2_2_1_3.setMenuName("自营预算机械成本");
		WebMenu_menu1_2_2_1_3.setMenuOpName("zyjx_web");
		WebMenu_menu1_2_2_1_3.setAction("../account/goal/machineryList.html");
		WebMenu_menu1_2_2_1_3.setIcon("left2");
		WebMenu_menu1_2_2_1_3.setParentMenuId("1,2,2,1");
		WebMenu_menu1_2_2_1.getChidren().add(WebMenu_menu1_2_2_1_3);
		MenuObj WebMenu_menu1_2_2_1_3_1 = new MenuObj();
		WebMenu_menu1_2_2_1_3_1.setMenuId("1,2,2,1,3,1");
		WebMenu_menu1_2_2_1_3_1.setMenuName("编辑");
		WebMenu_menu1_2_2_1_3_1.setMenuOpName("zyjx_web_ed");
		WebMenu_menu1_2_2_1_3_1.setAction("");
		WebMenu_menu1_2_2_1_3_1.setIcon("");
		WebMenu_menu1_2_2_1_3_1.setParentMenuId("1,2,2,1,3");
		WebMenu_menu1_2_2_1_3.getChidren().add(WebMenu_menu1_2_2_1_3_1);
		MenuObj WebMenu_menu1_2_2_1_3_2 = new MenuObj();
		WebMenu_menu1_2_2_1_3_2.setMenuId("1,2,2,1,3,2");
		WebMenu_menu1_2_2_1_3_2.setMenuName("删除");
		WebMenu_menu1_2_2_1_3_2.setMenuOpName("zyjx_web_del");
		WebMenu_menu1_2_2_1_3_2.setAction("");
		WebMenu_menu1_2_2_1_3_2.setIcon("");
		WebMenu_menu1_2_2_1_3_2.setParentMenuId("1,2,2,1,3");
		WebMenu_menu1_2_2_1_3.getChidren().add(WebMenu_menu1_2_2_1_3_2);
		MenuObj WebMenu_menu1_2_2_1_4 = new MenuObj();
		WebMenu_menu1_2_2_1_4.setMenuId("1,2,2,1,4");
		WebMenu_menu1_2_2_1_4.setMenuName("自营预算其他费用");
		WebMenu_menu1_2_2_1_4.setMenuOpName("zyqt_web");
		WebMenu_menu1_2_2_1_4.setAction("../account/goal/otherCostList.html");
		WebMenu_menu1_2_2_1_4.setIcon("left2");
		WebMenu_menu1_2_2_1_4.setParentMenuId("1,2,2,1");
		WebMenu_menu1_2_2_1.getChidren().add(WebMenu_menu1_2_2_1_4);
		MenuObj WebMenu_menu1_2_2_1_4_1 = new MenuObj();
		WebMenu_menu1_2_2_1_4_1.setMenuId("1,2,2,1,4,1");
		WebMenu_menu1_2_2_1_4_1.setMenuName("编辑");
		WebMenu_menu1_2_2_1_4_1.setMenuOpName("zyqt_web_ed");
		WebMenu_menu1_2_2_1_4_1.setAction("");
		WebMenu_menu1_2_2_1_4_1.setIcon("");
		WebMenu_menu1_2_2_1_4_1.setParentMenuId("1,2,2,1,4");
		WebMenu_menu1_2_2_1_4.getChidren().add(WebMenu_menu1_2_2_1_4_1);
		MenuObj WebMenu_menu1_2_2_1_4_2 = new MenuObj();
		WebMenu_menu1_2_2_1_4_2.setMenuId("1,2,2,1,4,2");
		WebMenu_menu1_2_2_1_4_2.setMenuName("删除");
		WebMenu_menu1_2_2_1_4_2.setMenuOpName("zyqt_web_del");
		WebMenu_menu1_2_2_1_4_2.setAction("");
		WebMenu_menu1_2_2_1_4_2.setIcon("");
		WebMenu_menu1_2_2_1_4_2.setParentMenuId("1,2,2,1,4");
		WebMenu_menu1_2_2_1_4.getChidren().add(WebMenu_menu1_2_2_1_4_2);
		MenuObj WebMenu_menu1_2_2_2 = new MenuObj();
		WebMenu_menu1_2_2_2.setMenuId("1,2,2,2");
		WebMenu_menu1_2_2_2.setMenuName("分包预算");
		WebMenu_menu1_2_2_2.setMenuOpName("fbys_web");
		WebMenu_menu1_2_2_2.setAction("");
		WebMenu_menu1_2_2_2.setIcon("left1");
		WebMenu_menu1_2_2_2.setParentMenuId("1,2,2");
		WebMenu_menu1_2_2.getChidren().add(WebMenu_menu1_2_2_2);
		MenuObj WebMenu_menu1_2_2_2_1 = new MenuObj();
		WebMenu_menu1_2_2_2_1.setMenuId("1,2,2,2,1");
		WebMenu_menu1_2_2_2_1.setMenuName("分包工程");
		WebMenu_menu1_2_2_2_1.setMenuOpName("fbgc_web");
		WebMenu_menu1_2_2_2_1.setAction("../account/goal/projectList.html");
		WebMenu_menu1_2_2_2_1.setIcon("left2");
		WebMenu_menu1_2_2_2_1.setParentMenuId("1,2,2,2");
		WebMenu_menu1_2_2_2.getChidren().add(WebMenu_menu1_2_2_2_1);
		MenuObj WebMenu_menu1_2_2_2_1_1 = new MenuObj();
		WebMenu_menu1_2_2_2_1_1.setMenuId("1,2,2,2,1,1");
		WebMenu_menu1_2_2_2_1_1.setMenuName("编辑");
		WebMenu_menu1_2_2_2_1_1.setMenuOpName("fbgc_web_ed");
		WebMenu_menu1_2_2_2_1_1.setAction("");
		WebMenu_menu1_2_2_2_1_1.setIcon("");
		WebMenu_menu1_2_2_2_1_1.setParentMenuId("1,2,2,2,1");
		WebMenu_menu1_2_2_2_1.getChidren().add(WebMenu_menu1_2_2_2_1_1);
		MenuObj WebMenu_menu1_2_2_2_1_2 = new MenuObj();
		WebMenu_menu1_2_2_2_1_2.setMenuId("1,2,2,2,1,2");
		WebMenu_menu1_2_2_2_1_2.setMenuName("删除");
		WebMenu_menu1_2_2_2_1_2.setMenuOpName("fbgc_web_del");
		WebMenu_menu1_2_2_2_1_2.setAction("");
		WebMenu_menu1_2_2_2_1_2.setIcon("");
		WebMenu_menu1_2_2_2_1_2.setParentMenuId("1,2,2,2,1");
		WebMenu_menu1_2_2_2_1.getChidren().add(WebMenu_menu1_2_2_2_1_2);
		MenuObj WebMenu_menu1_2_2_2_2 = new MenuObj();
		WebMenu_menu1_2_2_2_2.setMenuId("1,2,2,2,2");
		WebMenu_menu1_2_2_2_2.setMenuName("分包材料成本");
		WebMenu_menu1_2_2_2_2.setMenuOpName("fbcl_web");
		WebMenu_menu1_2_2_2_2.setAction("../account/goal/materialCostList.html");
		WebMenu_menu1_2_2_2_2.setIcon("left2");
		WebMenu_menu1_2_2_2_2.setParentMenuId("1,2,2,2");
		WebMenu_menu1_2_2_2.getChidren().add(WebMenu_menu1_2_2_2_2);
		MenuObj WebMenu_menu1_2_2_2_2_1 = new MenuObj();
		WebMenu_menu1_2_2_2_2_1.setMenuId("1,2,2,2,2,1");
		WebMenu_menu1_2_2_2_2_1.setMenuName("编辑");
		WebMenu_menu1_2_2_2_2_1.setMenuOpName("fbcl_web_ed");
		WebMenu_menu1_2_2_2_2_1.setAction("");
		WebMenu_menu1_2_2_2_2_1.setIcon("");
		WebMenu_menu1_2_2_2_2_1.setParentMenuId("1,2,2,2,2");
		WebMenu_menu1_2_2_2_2.getChidren().add(WebMenu_menu1_2_2_2_2_1);
		MenuObj WebMenu_menu1_2_2_2_2_2 = new MenuObj();
		WebMenu_menu1_2_2_2_2_2.setMenuId("1,2,2,2,2,2");
		WebMenu_menu1_2_2_2_2_2.setMenuName("删除");
		WebMenu_menu1_2_2_2_2_2.setMenuOpName("fbcl_web_del");
		WebMenu_menu1_2_2_2_2_2.setAction("");
		WebMenu_menu1_2_2_2_2_2.setIcon("");
		WebMenu_menu1_2_2_2_2_2.setParentMenuId("1,2,2,2,2");
		WebMenu_menu1_2_2_2_2.getChidren().add(WebMenu_menu1_2_2_2_2_2);
		MenuObj WebMenu_menu1_2_2_2_3 = new MenuObj();
		WebMenu_menu1_2_2_2_3.setMenuId("1,2,2,2,3");
		WebMenu_menu1_2_2_2_3.setMenuName("分包临建项目");
		WebMenu_menu1_2_2_2_3.setMenuOpName("fblj_web");
		WebMenu_menu1_2_2_2_3.setAction("../account/goal/provisionalCostList.html");
		WebMenu_menu1_2_2_2_3.setIcon("left2");
		WebMenu_menu1_2_2_2_3.setParentMenuId("1,2,2,2");
		WebMenu_menu1_2_2_2.getChidren().add(WebMenu_menu1_2_2_2_3);
		MenuObj WebMenu_menu1_2_2_2_3_1 = new MenuObj();
		WebMenu_menu1_2_2_2_3_1.setMenuId("1,2,2,2,3,1");
		WebMenu_menu1_2_2_2_3_1.setMenuName("编辑");
		WebMenu_menu1_2_2_2_3_1.setMenuOpName("fblj_web_ed");
		WebMenu_menu1_2_2_2_3_1.setAction("");
		WebMenu_menu1_2_2_2_3_1.setIcon("");
		WebMenu_menu1_2_2_2_3_1.setParentMenuId("1,2,2,2,3");
		WebMenu_menu1_2_2_2_3.getChidren().add(WebMenu_menu1_2_2_2_3_1);
		MenuObj WebMenu_menu1_2_2_2_3_2 = new MenuObj();
		WebMenu_menu1_2_2_2_3_2.setMenuId("1,2,2,2,3,2");
		WebMenu_menu1_2_2_2_3_2.setMenuName("删除");
		WebMenu_menu1_2_2_2_3_2.setMenuOpName("fblj_web_del");
		WebMenu_menu1_2_2_2_3_2.setAction("");
		WebMenu_menu1_2_2_2_3_2.setIcon("");
		WebMenu_menu1_2_2_2_3_2.setParentMenuId("1,2,2,2,3");
		WebMenu_menu1_2_2_2_3.getChidren().add(WebMenu_menu1_2_2_2_3_2);
		MenuObj WebMenu_menu1_2_3 = new MenuObj();
		WebMenu_menu1_2_3.setMenuId("1,2,3");
		WebMenu_menu1_2_3.setMenuName("管理费用");
		WebMenu_menu1_2_3.setMenuOpName("glfy_web");
		WebMenu_menu1_2_3.setAction("");
		WebMenu_menu1_2_3.setIcon("top3");
		WebMenu_menu1_2_3.setParentMenuId("1,2");
		WebMenu_menu1_2.getChidren().add(WebMenu_menu1_2_3);
		MenuObj WebMenu_menu1_2_3_1 = new MenuObj();
		WebMenu_menu1_2_3_1.setMenuId("1,2,3,1");
		WebMenu_menu1_2_3_1.setMenuName("管理费用预算");
		WebMenu_menu1_2_3_1.setMenuOpName("glfyys_web");
		WebMenu_menu1_2_3_1.setAction("../account/goal/manageCostList.html");
		WebMenu_menu1_2_3_1.setIcon("left1");
		WebMenu_menu1_2_3_1.setParentMenuId("1,2,3");
		WebMenu_menu1_2_3.getChidren().add(WebMenu_menu1_2_3_1);
		MenuObj WebMenu_menu1_2_3_1_1 = new MenuObj();
		WebMenu_menu1_2_3_1_1.setMenuId("1,2,3,1,1");
		WebMenu_menu1_2_3_1_1.setMenuName("编辑");
		WebMenu_menu1_2_3_1_1.setMenuOpName("glfyys_web_ed");
		WebMenu_menu1_2_3_1_1.setAction("");
		WebMenu_menu1_2_3_1_1.setIcon("");
		WebMenu_menu1_2_3_1_1.setParentMenuId("1,2,3,1");
		WebMenu_menu1_2_3_1.getChidren().add(WebMenu_menu1_2_3_1_1);
		MenuObj WebMenu_menu1_2_3_1_2 = new MenuObj();
		WebMenu_menu1_2_3_1_2.setMenuId("1,2,3,1,2");
		WebMenu_menu1_2_3_1_2.setMenuName("删除");
		WebMenu_menu1_2_3_1_2.setMenuOpName("glfyys_web_del");
		WebMenu_menu1_2_3_1_2.setAction("");
		WebMenu_menu1_2_3_1_2.setIcon("");
		WebMenu_menu1_2_3_1_2.setParentMenuId("1,2,3,1");
		WebMenu_menu1_2_3_1.getChidren().add(WebMenu_menu1_2_3_1_2);
		MenuObj WebMenu_menu1_2_4 = new MenuObj();
		WebMenu_menu1_2_4.setMenuId("1,2,4");
		WebMenu_menu1_2_4.setMenuName("预算汇总");
		WebMenu_menu1_2_4.setMenuOpName("yshz_web");
		WebMenu_menu1_2_4.setAction("");
		WebMenu_menu1_2_4.setIcon("top3");
		WebMenu_menu1_2_4.setParentMenuId("1,2");
		WebMenu_menu1_2.getChidren().add(WebMenu_menu1_2_4);
		MenuObj WebMenu_menu1_2_4_1 = new MenuObj();
		WebMenu_menu1_2_4_1.setMenuId("1,2,4,1");
		WebMenu_menu1_2_4_1.setMenuName("目标预算汇总");
		WebMenu_menu1_2_4_1.setMenuOpName("mbyshz_web");
		WebMenu_menu1_2_4_1.setAction("../account/goal/goalCostTotalList.html");
		WebMenu_menu1_2_4_1.setIcon("left1");
		WebMenu_menu1_2_4_1.setParentMenuId("1,2,4");
		WebMenu_menu1_2_4.getChidren().add(WebMenu_menu1_2_4_1);
		MenuObj WebMenu_menu2 = new MenuObj();
		WebMenu_menu2.setMenuId("2");
		WebMenu_menu2.setMenuName("收支管理");
		WebMenu_menu2.setMenuOpName("szgl_web");
		WebMenu_menu2.setAction("");
		WebMenu_menu2.setIcon("top1");
		WebMenu_menu2.setParentMenuId("0");
		WebMenu_menu2.setChidren(new ArrayList<MenuObj>());
		WebMenu_menuList.add(WebMenu_menu2);
		MenuObj WebMenu_menu2_1 = new MenuObj();
		WebMenu_menu2_1.setMenuId("2,1");
		WebMenu_menu2_1.setMenuName("收入");
		WebMenu_menu2_1.setMenuOpName("sr_web");
		WebMenu_menu2_1.setAction("");
		WebMenu_menu2_1.setIcon("top2");
		WebMenu_menu2_1.setParentMenuId("2");
		WebMenu_menu2.getChidren().add(WebMenu_menu2_1);
		MenuObj WebMenu_menu2_1_1 = new MenuObj();
		WebMenu_menu2_1_1.setMenuId("2,1,1");
		WebMenu_menu2_1_1.setMenuName("结算收入");
		WebMenu_menu2_1_1.setMenuOpName("jssr_web");
		WebMenu_menu2_1_1.setAction("../budget/income/incomeCountList.html");
		WebMenu_menu2_1_1.setIcon("left1");
		WebMenu_menu2_1_1.setParentMenuId("2,1");
		WebMenu_menu2_1.getChidren().add(WebMenu_menu2_1_1);
		MenuObj WebMenu_menu2_1_1_1 = new MenuObj();
		WebMenu_menu2_1_1_1.setMenuId("2,1,1,1");
		WebMenu_menu2_1_1_1.setMenuName("删除");
		WebMenu_menu2_1_1_1.setMenuOpName("jssr_web_del");
		WebMenu_menu2_1_1_1.setAction("");
		WebMenu_menu2_1_1_1.setIcon("");
		WebMenu_menu2_1_1_1.setParentMenuId("2,1,1");
		WebMenu_menu2_1_1.getChidren().add(WebMenu_menu2_1_1_1);
		MenuObj WebMenu_menu2_1_1_2 = new MenuObj();
		WebMenu_menu2_1_1_2.setMenuId("2,1,1,2");
		WebMenu_menu2_1_1_2.setMenuName("查看金额");
		WebMenu_menu2_1_1_2.setMenuOpName("jssr_web_price");
		WebMenu_menu2_1_1_2.setAction("");
		WebMenu_menu2_1_1_2.setIcon("");
		WebMenu_menu2_1_1_2.setParentMenuId("2,1,1");
		WebMenu_menu2_1_1.getChidren().add(WebMenu_menu2_1_1_2);
		MenuObj WebMenu_menu2_1_2 = new MenuObj();
		WebMenu_menu2_1_2.setMenuId("2,1,2");
		WebMenu_menu2_1_2.setMenuName("新增收入量统计");
		WebMenu_menu2_1_2.setMenuOpName("xzsr_web");
		WebMenu_menu2_1_2.setAction("../budget/income/otherIncomeList.html");
		WebMenu_menu2_1_2.setIcon("left1");
		WebMenu_menu2_1_2.setParentMenuId("2,1");
		WebMenu_menu2_1.getChidren().add(WebMenu_menu2_1_2);
		MenuObj WebMenu_menu2_1_2_1 = new MenuObj();
		WebMenu_menu2_1_2_1.setMenuId("2,1,2,1");
		WebMenu_menu2_1_2_1.setMenuName("编辑");
		WebMenu_menu2_1_2_1.setMenuOpName("xzsr_web_ed");
		WebMenu_menu2_1_2_1.setAction("");
		WebMenu_menu2_1_2_1.setIcon("");
		WebMenu_menu2_1_2_1.setParentMenuId("2,1,2");
		WebMenu_menu2_1_2.getChidren().add(WebMenu_menu2_1_2_1);
		MenuObj WebMenu_menu2_1_2_2 = new MenuObj();
		WebMenu_menu2_1_2_2.setMenuId("2,1,2,2");
		WebMenu_menu2_1_2_2.setMenuName("删除");
		WebMenu_menu2_1_2_2.setMenuOpName("xzsr_web_del");
		WebMenu_menu2_1_2_2.setAction("");
		WebMenu_menu2_1_2_2.setIcon("");
		WebMenu_menu2_1_2_2.setParentMenuId("2,1,2");
		WebMenu_menu2_1_2.getChidren().add(WebMenu_menu2_1_2_2);
		MenuObj WebMenu_menu2_1_3 = new MenuObj();
		WebMenu_menu2_1_3.setMenuId("2,1,3");
		WebMenu_menu2_1_3.setMenuName("新增收入价格统计");
		WebMenu_menu2_1_3.setMenuOpName("xzsrjg_web");
		WebMenu_menu2_1_3.setAction("../budget/income/otherIncomePriceList.html");
		WebMenu_menu2_1_3.setIcon("left1");
		WebMenu_menu2_1_3.setParentMenuId("2,1");
		WebMenu_menu2_1.getChidren().add(WebMenu_menu2_1_3);
		MenuObj WebMenu_menu2_1_3_1 = new MenuObj();
		WebMenu_menu2_1_3_1.setMenuId("2,1,3,1");
		WebMenu_menu2_1_3_1.setMenuName("编辑");
		WebMenu_menu2_1_3_1.setMenuOpName("xzsrjg_web_ed");
		WebMenu_menu2_1_3_1.setAction("");
		WebMenu_menu2_1_3_1.setIcon("");
		WebMenu_menu2_1_3_1.setParentMenuId("2,1,3");
		WebMenu_menu2_1_3.getChidren().add(WebMenu_menu2_1_3_1);
		MenuObj WebMenu_menu2_1_3_2 = new MenuObj();
		WebMenu_menu2_1_3_2.setMenuId("2,1,3,2");
		WebMenu_menu2_1_3_2.setMenuName("删除");
		WebMenu_menu2_1_3_2.setMenuOpName("xzsrjg_web_del");
		WebMenu_menu2_1_3_2.setAction("");
		WebMenu_menu2_1_3_2.setIcon("");
		WebMenu_menu2_1_3_2.setParentMenuId("2,1,3");
		WebMenu_menu2_1_3.getChidren().add(WebMenu_menu2_1_3_2);
		MenuObj WebMenu_menu2_2 = new MenuObj();
		WebMenu_menu2_2.setMenuId("2,2");
		WebMenu_menu2_2.setMenuName("支出间接成本");
		WebMenu_menu2_2.setMenuOpName("zcjjcb_web");
		WebMenu_menu2_2.setAction("");
		WebMenu_menu2_2.setIcon("top2");
		WebMenu_menu2_2.setParentMenuId("2");
		WebMenu_menu2.getChidren().add(WebMenu_menu2_2);
		MenuObj WebMenu_menu2_2_1 = new MenuObj();
		WebMenu_menu2_2_1.setMenuId("2,2,1");
		WebMenu_menu2_2_1.setMenuName("支出间接成本列表");
		WebMenu_menu2_2_1.setMenuOpName("zcjjcblb_web");
		WebMenu_menu2_2_1.setAction("../budget/expenses/indirectCostList.html");
		WebMenu_menu2_2_1.setIcon("left1");
		WebMenu_menu2_2_1.setParentMenuId("2,2");
		WebMenu_menu2_2.getChidren().add(WebMenu_menu2_2_1);
		MenuObj WebMenu_menu2_2_1_1 = new MenuObj();
		WebMenu_menu2_2_1_1.setMenuId("2,2,1,1");
		WebMenu_menu2_2_1_1.setMenuName("删除");
		WebMenu_menu2_2_1_1.setMenuOpName("zcjjcblb_web_del");
		WebMenu_menu2_2_1_1.setAction("");
		WebMenu_menu2_2_1_1.setIcon("");
		WebMenu_menu2_2_1_1.setParentMenuId("2,2,1");
		WebMenu_menu2_2_1.getChidren().add(WebMenu_menu2_2_1_1);
		MenuObj WebMenu_menu2_3 = new MenuObj();
		WebMenu_menu2_3.setMenuId("2,3");
		WebMenu_menu2_3.setMenuName("支出直接成本");
		WebMenu_menu2_3.setMenuOpName("zczjcb_web");
		WebMenu_menu2_3.setAction("");
		WebMenu_menu2_3.setIcon("top2");
		WebMenu_menu2_3.setParentMenuId("2");
		WebMenu_menu2.getChidren().add(WebMenu_menu2_3);
		MenuObj WebMenu_menu2_3_1 = new MenuObj();
		WebMenu_menu2_3_1.setMenuId("2,3,1");
		WebMenu_menu2_3_1.setMenuName("自营成本");
		WebMenu_menu2_3_1.setMenuOpName("zycb_web");
		WebMenu_menu2_3_1.setAction("");
		WebMenu_menu2_3_1.setIcon("left1");
		WebMenu_menu2_3_1.setParentMenuId("2,3");
		WebMenu_menu2_3.getChidren().add(WebMenu_menu2_3_1);
		MenuObj WebMenu_menu2_3_1_1 = new MenuObj();
		WebMenu_menu2_3_1_1.setMenuId("2,3,1,1");
		WebMenu_menu2_3_1_1.setMenuName("实际材料成本");
		WebMenu_menu2_3_1_1.setMenuOpName("sjclcb_web");
		WebMenu_menu2_3_1_1.setAction("../budget/expenses/directCost/selfCost/materialCostList.html");
		WebMenu_menu2_3_1_1.setIcon("left2");
		WebMenu_menu2_3_1_1.setParentMenuId("2,3,1");
		WebMenu_menu2_3_1.getChidren().add(WebMenu_menu2_3_1_1);
		MenuObj WebMenu_menu2_3_1_1_1 = new MenuObj();
		WebMenu_menu2_3_1_1_1.setMenuId("2,3,1,1,1");
		WebMenu_menu2_3_1_1_1.setMenuName("删除");
		WebMenu_menu2_3_1_1_1.setMenuOpName("sjclcb_web_del");
		WebMenu_menu2_3_1_1_1.setAction("");
		WebMenu_menu2_3_1_1_1.setIcon("");
		WebMenu_menu2_3_1_1_1.setParentMenuId("2,3,1,1");
		WebMenu_menu2_3_1_1.getChidren().add(WebMenu_menu2_3_1_1_1);
		MenuObj WebMenu_menu2_3_1_2 = new MenuObj();
		WebMenu_menu2_3_1_2.setMenuId("2,3,1,2");
		WebMenu_menu2_3_1_2.setMenuName("实际机械成本");
		WebMenu_menu2_3_1_2.setMenuOpName("sjjxcb_web");
		WebMenu_menu2_3_1_2.setAction("../budget/expenses/directCost/selfCost/machineryList.html");
		WebMenu_menu2_3_1_2.setIcon("left2");
		WebMenu_menu2_3_1_2.setParentMenuId("2,3,1");
		WebMenu_menu2_3_1.getChidren().add(WebMenu_menu2_3_1_2);
		MenuObj WebMenu_menu2_3_1_2_1 = new MenuObj();
		WebMenu_menu2_3_1_2_1.setMenuId("2,3,1,2,1");
		WebMenu_menu2_3_1_2_1.setMenuName("删除");
		WebMenu_menu2_3_1_2_1.setMenuOpName("sjjxcb_web_del");
		WebMenu_menu2_3_1_2_1.setAction("");
		WebMenu_menu2_3_1_2_1.setIcon("");
		WebMenu_menu2_3_1_2_1.setParentMenuId("2,3,1,2");
		WebMenu_menu2_3_1_2.getChidren().add(WebMenu_menu2_3_1_2_1);
		MenuObj WebMenu_menu2_3_1_3 = new MenuObj();
		WebMenu_menu2_3_1_3.setMenuId("2,3,1,3");
		WebMenu_menu2_3_1_3.setMenuName("实际零星用工");
		WebMenu_menu2_3_1_3.setMenuOpName("sjlxygcb_web");
		WebMenu_menu2_3_1_3.setAction("../budget/expenses/directCost/selfCost/workerCostList.html");
		WebMenu_menu2_3_1_3.setIcon("left2");
		WebMenu_menu2_3_1_3.setParentMenuId("2,3,1");
		WebMenu_menu2_3_1.getChidren().add(WebMenu_menu2_3_1_3);
		MenuObj WebMenu_menu2_3_1_3_1 = new MenuObj();
		WebMenu_menu2_3_1_3_1.setMenuId("2,3,1,3,1");
		WebMenu_menu2_3_1_3_1.setMenuName("删除");
		WebMenu_menu2_3_1_3_1.setMenuOpName("sjlxygcb_web_del");
		WebMenu_menu2_3_1_3_1.setAction("");
		WebMenu_menu2_3_1_3_1.setIcon("");
		WebMenu_menu2_3_1_3_1.setParentMenuId("2,3,1,3");
		WebMenu_menu2_3_1_3.getChidren().add(WebMenu_menu2_3_1_3_1);
		MenuObj WebMenu_menu2_3_1_4 = new MenuObj();
		WebMenu_menu2_3_1_4.setMenuId("2,3,1,4");
		WebMenu_menu2_3_1_4.setMenuName("实际其他费用");
		WebMenu_menu2_3_1_4.setMenuOpName("sjqtfy_web");
		WebMenu_menu2_3_1_4.setAction("../budget/expenses/directCost/selfCost/otherCostList.html");
		WebMenu_menu2_3_1_4.setIcon("left2");
		WebMenu_menu2_3_1_4.setParentMenuId("2,3,1");
		WebMenu_menu2_3_1.getChidren().add(WebMenu_menu2_3_1_4);
		MenuObj WebMenu_menu2_3_1_4_1 = new MenuObj();
		WebMenu_menu2_3_1_4_1.setMenuId("2,3,1,4,1");
		WebMenu_menu2_3_1_4_1.setMenuName("删除");
		WebMenu_menu2_3_1_4_1.setMenuOpName("sjqtfy_web_del");
		WebMenu_menu2_3_1_4_1.setAction("");
		WebMenu_menu2_3_1_4_1.setIcon("");
		WebMenu_menu2_3_1_4_1.setParentMenuId("2,3,1,4");
		WebMenu_menu2_3_1_4.getChidren().add(WebMenu_menu2_3_1_4_1);
		MenuObj WebMenu_menu2_3_2 = new MenuObj();
		WebMenu_menu2_3_2.setMenuId("2,3,2");
		WebMenu_menu2_3_2.setMenuName("分包成本");
		WebMenu_menu2_3_2.setMenuOpName("fbcb_web");
		WebMenu_menu2_3_2.setAction("");
		WebMenu_menu2_3_2.setIcon("left1");
		WebMenu_menu2_3_2.setParentMenuId("2,3");
		WebMenu_menu2_3.getChidren().add(WebMenu_menu2_3_2);
		MenuObj WebMenu_menu2_3_2_1 = new MenuObj();
		WebMenu_menu2_3_2_1.setMenuId("2,3,2,1");
		WebMenu_menu2_3_2_1.setMenuName("分包量统计");
		WebMenu_menu2_3_2_1.setMenuOpName("fbltj_web");
		WebMenu_menu2_3_2_1.setAction("../budget/expenses/directCost/fbCost/fbQuantitiesList.html");
		WebMenu_menu2_3_2_1.setIcon("left2");
		WebMenu_menu2_3_2_1.setParentMenuId("2,3,2");
		WebMenu_menu2_3_2.getChidren().add(WebMenu_menu2_3_2_1);
		MenuObj WebMenu_menu2_3_2_1_1 = new MenuObj();
		WebMenu_menu2_3_2_1_1.setMenuId("2,3,2,1,1");
		WebMenu_menu2_3_2_1_1.setMenuName("删除");
		WebMenu_menu2_3_2_1_1.setMenuOpName("fbltj_web_del");
		WebMenu_menu2_3_2_1_1.setAction("");
		WebMenu_menu2_3_2_1_1.setIcon("");
		WebMenu_menu2_3_2_1_1.setParentMenuId("2,3,2,1");
		WebMenu_menu2_3_2_1.getChidren().add(WebMenu_menu2_3_2_1_1);
		MenuObj WebMenu_menu2_3_2_2 = new MenuObj();
		WebMenu_menu2_3_2_2.setMenuId("2,3,2,2");
		WebMenu_menu2_3_2_2.setMenuName("分包价格统计");
		WebMenu_menu2_3_2_2.setMenuOpName("fbjggl_web");
		WebMenu_menu2_3_2_2.setAction("../budget/expenses/directCost/fbCost/fbPriceList.html");
		WebMenu_menu2_3_2_2.setIcon("left2");
		WebMenu_menu2_3_2_2.setParentMenuId("2,3,2");
		WebMenu_menu2_3_2.getChidren().add(WebMenu_menu2_3_2_2);
		MenuObj WebMenu_menu2_3_2_2_1 = new MenuObj();
		WebMenu_menu2_3_2_2_1.setMenuId("2,3,2,2,1");
		WebMenu_menu2_3_2_2_1.setMenuName("编辑");
		WebMenu_menu2_3_2_2_1.setMenuOpName("fbjggl_web_ed");
		WebMenu_menu2_3_2_2_1.setAction("");
		WebMenu_menu2_3_2_2_1.setIcon("");
		WebMenu_menu2_3_2_2_1.setParentMenuId("2,3,2,2");
		WebMenu_menu2_3_2_2.getChidren().add(WebMenu_menu2_3_2_2_1);
		MenuObj WebMenu_menu2_3_2_2_2 = new MenuObj();
		WebMenu_menu2_3_2_2_2.setMenuId("2,3,2,2,2");
		WebMenu_menu2_3_2_2_2.setMenuName("删除");
		WebMenu_menu2_3_2_2_2.setMenuOpName("fbjggl_web_del");
		WebMenu_menu2_3_2_2_2.setAction("");
		WebMenu_menu2_3_2_2_2.setIcon("");
		WebMenu_menu2_3_2_2_2.setParentMenuId("2,3,2,2");
		WebMenu_menu2_3_2_2.getChidren().add(WebMenu_menu2_3_2_2_2);
		MenuObj WebMenu_menu2_3_2_3 = new MenuObj();
		WebMenu_menu2_3_2_3.setMenuId("2,3,2,3");
		WebMenu_menu2_3_2_3.setMenuName("临建支出量统计");
		WebMenu_menu2_3_2_3.setMenuOpName("ljzc_web");
		WebMenu_menu2_3_2_3.setAction("../budget/expenses/directCost/fbCost/tempProjectList.html");
		WebMenu_menu2_3_2_3.setIcon("left2");
		WebMenu_menu2_3_2_3.setParentMenuId("2,3,2");
		WebMenu_menu2_3_2.getChidren().add(WebMenu_menu2_3_2_3);
		MenuObj WebMenu_menu2_3_2_3_1 = new MenuObj();
		WebMenu_menu2_3_2_3_1.setMenuId("2,3,2,3,1");
		WebMenu_menu2_3_2_3_1.setMenuName("删除");
		WebMenu_menu2_3_2_3_1.setMenuOpName("ljzc_web_del");
		WebMenu_menu2_3_2_3_1.setAction("");
		WebMenu_menu2_3_2_3_1.setIcon("");
		WebMenu_menu2_3_2_3_1.setParentMenuId("2,3,2,3");
		WebMenu_menu2_3_2_3.getChidren().add(WebMenu_menu2_3_2_3_1);
		MenuObj WebMenu_menu2_3_2_4 = new MenuObj();
		WebMenu_menu2_3_2_4.setMenuId("2,3,2,4");
		WebMenu_menu2_3_2_4.setMenuName("临建支出价格统计");
		WebMenu_menu2_3_2_4.setMenuOpName("ljzcjg_web");
		WebMenu_menu2_3_2_4.setAction("../budget/expenses/directCost/fbCost/tempProjectPriceList.html");
		WebMenu_menu2_3_2_4.setIcon("left2");
		WebMenu_menu2_3_2_4.setParentMenuId("2,3,2");
		WebMenu_menu2_3_2.getChidren().add(WebMenu_menu2_3_2_4);
		MenuObj WebMenu_menu2_3_2_4_1 = new MenuObj();
		WebMenu_menu2_3_2_4_1.setMenuId("2,3,2,4,1");
		WebMenu_menu2_3_2_4_1.setMenuName("编辑");
		WebMenu_menu2_3_2_4_1.setMenuOpName("ljzcjg_web_ed");
		WebMenu_menu2_3_2_4_1.setAction("");
		WebMenu_menu2_3_2_4_1.setIcon("");
		WebMenu_menu2_3_2_4_1.setParentMenuId("2,3,2,4");
		WebMenu_menu2_3_2_4.getChidren().add(WebMenu_menu2_3_2_4_1);
		MenuObj WebMenu_menu2_3_2_4_2 = new MenuObj();
		WebMenu_menu2_3_2_4_2.setMenuId("2,3,2,4,2");
		WebMenu_menu2_3_2_4_2.setMenuName("删除");
		WebMenu_menu2_3_2_4_2.setMenuOpName("ljzcjg_web_del");
		WebMenu_menu2_3_2_4_2.setAction("");
		WebMenu_menu2_3_2_4_2.setIcon("");
		WebMenu_menu2_3_2_4_2.setParentMenuId("2,3,2,4");
		WebMenu_menu2_3_2_4.getChidren().add(WebMenu_menu2_3_2_4_2);
		MenuObj WebMenu_menu2_4 = new MenuObj();
		WebMenu_menu2_4.setMenuId("2,4");
		WebMenu_menu2_4.setMenuName("管理费用");
		WebMenu_menu2_4.setMenuOpName("glfy_web");
		WebMenu_menu2_4.setAction("");
		WebMenu_menu2_4.setIcon("top2");
		WebMenu_menu2_4.setParentMenuId("2");
		WebMenu_menu2.getChidren().add(WebMenu_menu2_4);
		MenuObj WebMenu_menu2_4_1 = new MenuObj();
		WebMenu_menu2_4_1.setMenuId("2,4,1");
		WebMenu_menu2_4_1.setMenuName("管理费用列表");
		WebMenu_menu2_4_1.setMenuOpName("glfylb_web");
		WebMenu_menu2_4_1.setAction("../budget/expenses/manageCostList.html");
		WebMenu_menu2_4_1.setIcon("left1");
		WebMenu_menu2_4_1.setParentMenuId("2,4");
		WebMenu_menu2_4.getChidren().add(WebMenu_menu2_4_1);
		MenuObj WebMenu_menu2_4_1_1 = new MenuObj();
		WebMenu_menu2_4_1_1.setMenuId("2,4,1,1");
		WebMenu_menu2_4_1_1.setMenuName("删除");
		WebMenu_menu2_4_1_1.setMenuOpName("glfylb_web_del");
		WebMenu_menu2_4_1_1.setAction("");
		WebMenu_menu2_4_1_1.setIcon("");
		WebMenu_menu2_4_1_1.setParentMenuId("2,4,1");
		WebMenu_menu2_4_1.getChidren().add(WebMenu_menu2_4_1_1);
		MenuObj WebMenu_menu2_5 = new MenuObj();
		WebMenu_menu2_5.setMenuId("2,5");
		WebMenu_menu2_5.setMenuName("资源统计");
		WebMenu_menu2_5.setMenuOpName("zytj_web");
		WebMenu_menu2_5.setAction("");
		WebMenu_menu2_5.setIcon("top2");
		WebMenu_menu2_5.setParentMenuId("2");
		WebMenu_menu2.getChidren().add(WebMenu_menu2_5);
		MenuObj WebMenu_menu2_5_1 = new MenuObj();
		WebMenu_menu2_5_1.setMenuId("2,5,1");
		WebMenu_menu2_5_1.setMenuName("分包商统计");
		WebMenu_menu2_5_1.setMenuOpName("fbstj_web");
		WebMenu_menu2_5_1.setAction("../resource/resourceStateList.html");
		WebMenu_menu2_5_1.setIcon("left1");
		WebMenu_menu2_5_1.setParentMenuId("2,5");
		WebMenu_menu2_5.getChidren().add(WebMenu_menu2_5_1);
		MenuObj WebMenu_menu2_5_1_1 = new MenuObj();
		WebMenu_menu2_5_1_1.setMenuId("2,5,1,1");
		WebMenu_menu2_5_1_1.setMenuName("删除");
		WebMenu_menu2_5_1_1.setMenuOpName("fbstj_web_del");
		WebMenu_menu2_5_1_1.setAction("");
		WebMenu_menu2_5_1_1.setIcon("");
		WebMenu_menu2_5_1_1.setParentMenuId("2,5,1");
		WebMenu_menu2_5_1.getChidren().add(WebMenu_menu2_5_1_1);
		MenuObj WebMenu_menu2_5_2 = new MenuObj();
		WebMenu_menu2_5_2.setMenuId("2,5,2");
		WebMenu_menu2_5_2.setMenuName("重点部位工序核算");
		WebMenu_menu2_5_2.setMenuOpName("zdbwgxhs_web");
		WebMenu_menu2_5_2.setAction("../resource/resourceProcessList.html");
		WebMenu_menu2_5_2.setIcon("left1");
		WebMenu_menu2_5_2.setParentMenuId("2,5");
		WebMenu_menu2_5.getChidren().add(WebMenu_menu2_5_2);
		MenuObj WebMenu_menu2_5_2_1 = new MenuObj();
		WebMenu_menu2_5_2_1.setMenuId("2,5,2,1");
		WebMenu_menu2_5_2_1.setMenuName("编辑");
		WebMenu_menu2_5_2_1.setMenuOpName("zdbwgxhs_web_ed");
		WebMenu_menu2_5_2_1.setAction("");
		WebMenu_menu2_5_2_1.setIcon("");
		WebMenu_menu2_5_2_1.setParentMenuId("2,5,2");
		WebMenu_menu2_5_2.getChidren().add(WebMenu_menu2_5_2_1);
		MenuObj WebMenu_menu2_5_2_2 = new MenuObj();
		WebMenu_menu2_5_2_2.setMenuId("2,5,2,2");
		WebMenu_menu2_5_2_2.setMenuName("删除");
		WebMenu_menu2_5_2_2.setMenuOpName("zdbwgxhs_web_del");
		WebMenu_menu2_5_2_2.setAction("");
		WebMenu_menu2_5_2_2.setIcon("");
		WebMenu_menu2_5_2_2.setParentMenuId("2,5,2");
		WebMenu_menu2_5_2.getChidren().add(WebMenu_menu2_5_2_2);
		MenuObj WebMenu_menu3 = new MenuObj();
		WebMenu_menu3.setMenuId("3");
		WebMenu_menu3.setMenuName("统计分析");
		WebMenu_menu3.setMenuOpName("tjfx_web");
		WebMenu_menu3.setAction("");
		WebMenu_menu3.setIcon("top1");
		WebMenu_menu3.setParentMenuId("0");
		WebMenu_menu3.setChidren(new ArrayList<MenuObj>());
		WebMenu_menuList.add(WebMenu_menu3);
		MenuObj WebMenu_menu3_1 = new MenuObj();
		WebMenu_menu3_1.setMenuId("3,1");
		WebMenu_menu3_1.setMenuName("成本收入报表");
		WebMenu_menu3_1.setMenuOpName("cbsubb_web");
		WebMenu_menu3_1.setAction("../report/reportBudget.html");
		WebMenu_menu3_1.setIcon("left1");
		WebMenu_menu3_1.setParentMenuId("3");
		WebMenu_menu3.getChidren().add(WebMenu_menu3_1);
		MenuObj WebMenu_menu3_2 = new MenuObj();
		WebMenu_menu3_2.setMenuId("3,2");
		WebMenu_menu3_2.setMenuName("资源统计报表");
		WebMenu_menu3_2.setMenuOpName("zytjbb_web");
		WebMenu_menu3_2.setAction("../report/reportResource.html");
		WebMenu_menu3_2.setIcon("left1");
		WebMenu_menu3_2.setParentMenuId("3");
		WebMenu_menu3.getChidren().add(WebMenu_menu3_2);
		MenuObj WebMenu_menu3_3 = new MenuObj();
		WebMenu_menu3_3.setMenuId("3,3");
		WebMenu_menu3_3.setMenuName("综合查询");
		WebMenu_menu3_3.setMenuOpName("zhcx_web");
		WebMenu_menu3_3.setAction("");
		WebMenu_menu3_3.setIcon("left1");
		WebMenu_menu3_3.setParentMenuId("3");
		WebMenu_menu3.getChidren().add(WebMenu_menu3_3);
		MenuObj WebMenu_menu3_3_1 = new MenuObj();
		WebMenu_menu3_3_1.setMenuId("3,3,1");
		WebMenu_menu3_3_1.setMenuName("每日数据");
		WebMenu_menu3_3_1.setMenuOpName("mrsj_web");
		WebMenu_menu3_3_1.setAction("../manage/dailyDataOpt.html");
		WebMenu_menu3_3_1.setIcon("left2");
		WebMenu_menu3_3_1.setParentMenuId("3,3");
		WebMenu_menu3_3.getChidren().add(WebMenu_menu3_3_1);
		MenuObj WebMenu_menu3_3_2 = new MenuObj();
		WebMenu_menu3_3_2.setMenuId("3,3,2");
		WebMenu_menu3_3_2.setMenuName("累计数据");
		WebMenu_menu3_3_2.setMenuOpName("ljsj_web");
		WebMenu_menu3_3_2.setAction("../manage/cumulativeDataList.html");
		WebMenu_menu3_3_2.setIcon("left2");
		WebMenu_menu3_3_2.setParentMenuId("3,3");
		WebMenu_menu3_3.getChidren().add(WebMenu_menu3_3_2);
		MenuObj WebMenu_menu3_4 = new MenuObj();
		WebMenu_menu3_4.setMenuId("3,4");
		WebMenu_menu3_4.setMenuName("材料核销");
		WebMenu_menu3_4.setMenuOpName("clhx_web");
		WebMenu_menu3_4.setAction("");
		WebMenu_menu3_4.setIcon("left1");
		WebMenu_menu3_4.setParentMenuId("3");
		WebMenu_menu3.getChidren().add(WebMenu_menu3_4);
		MenuObj WebMenu_menu3_4_1 = new MenuObj();
		WebMenu_menu3_4_1.setMenuId("3,4,1");
		WebMenu_menu3_4_1.setMenuName("分包材料核销");
		WebMenu_menu3_4_1.setMenuOpName("fbclhx_web");
		WebMenu_menu3_4_1.setAction("../manage/materialManage.html");
		WebMenu_menu3_4_1.setIcon("left2");
		WebMenu_menu3_4_1.setParentMenuId("3,4");
		WebMenu_menu3_4.getChidren().add(WebMenu_menu3_4_1);
		MenuObj WebMenu_menu3_4_2 = new MenuObj();
		WebMenu_menu3_4_2.setMenuId("3,4,2");
		WebMenu_menu3_4_2.setMenuName("自营材料核销");
		WebMenu_menu3_4_2.setMenuOpName("zyclhx_web");
		WebMenu_menu3_4_2.setAction("../manage/materialManage_self.html");
		WebMenu_menu3_4_2.setIcon("left2");
		WebMenu_menu3_4_2.setParentMenuId("3,4");
		WebMenu_menu3_4.getChidren().add(WebMenu_menu3_4_2);
		MenuObj WebMenu_menu4 = new MenuObj();
		WebMenu_menu4.setMenuId("4");
		WebMenu_menu4.setMenuName("审核");
		WebMenu_menu4.setMenuOpName("sh_web");
		WebMenu_menu4.setAction("");
		WebMenu_menu4.setIcon("top1");
		WebMenu_menu4.setParentMenuId("0");
		WebMenu_menu4.setChidren(new ArrayList<MenuObj>());
		WebMenu_menuList.add(WebMenu_menu4);
		MenuObj WebMenu_menu4_1 = new MenuObj();
		WebMenu_menu4_1.setMenuId("4,1");
		WebMenu_menu4_1.setMenuName("审核任务");
		WebMenu_menu4_1.setMenuOpName("shrw_web");
		WebMenu_menu4_1.setAction("../manage/auditTaskList.html");
		WebMenu_menu4_1.setIcon("left2");
		WebMenu_menu4_1.setParentMenuId("4");
		WebMenu_menu4.getChidren().add(WebMenu_menu4_1);
		MenuObj WebMenu_menu4_1_1 = new MenuObj();
		WebMenu_menu4_1_1.setMenuId("4,1,1");
		WebMenu_menu4_1_1.setMenuName("财务审核");
		WebMenu_menu4_1_1.setMenuOpName("spgl_web_cw");
		WebMenu_menu4_1_1.setAction("");
		WebMenu_menu4_1_1.setIcon("");
		WebMenu_menu4_1_1.setParentMenuId("4,1");
		WebMenu_menu4_1.getChidren().add(WebMenu_menu4_1_1);
		MenuObj WebMenu_menu4_2 = new MenuObj();
		WebMenu_menu4_2.setMenuId("4,2");
		WebMenu_menu4_2.setMenuName("审核请求");
		WebMenu_menu4_2.setMenuOpName("shqq_web");
		WebMenu_menu4_2.setAction("../manage/auditRequestList.html");
		WebMenu_menu4_2.setIcon("left2");
		WebMenu_menu4_2.setParentMenuId("4");
		WebMenu_menu4.getChidren().add(WebMenu_menu4_2);
		MenuObj WebMenu_menu5 = new MenuObj();
		WebMenu_menu5.setMenuId("5");
		WebMenu_menu5.setMenuName("财务");
		WebMenu_menu5.setMenuOpName("cw_web");
		WebMenu_menu5.setAction("");
		WebMenu_menu5.setIcon("top1");
		WebMenu_menu5.setParentMenuId("0");
		WebMenu_menu5.setChidren(new ArrayList<MenuObj>());
		WebMenu_menuList.add(WebMenu_menu5);
		MenuObj WebMenu_menu5_1 = new MenuObj();
		WebMenu_menu5_1.setMenuId("5,1");
		WebMenu_menu5_1.setMenuName("结算");
		WebMenu_menu5_1.setMenuOpName("js_web");
		WebMenu_menu5_1.setAction("");
		WebMenu_menu5_1.setIcon("top2");
		WebMenu_menu5_1.setParentMenuId("5");
		WebMenu_menu5.getChidren().add(WebMenu_menu5_1);
		MenuObj WebMenu_menu5_1_1 = new MenuObj();
		WebMenu_menu5_1_1.setMenuId("5,1,1");
		WebMenu_menu5_1_1.setMenuName("对上结算");
		WebMenu_menu5_1_1.setMenuOpName("dsjs_web");
		WebMenu_menu5_1_1.setAction("../finance/balanceUpList.html");
		WebMenu_menu5_1_1.setIcon("left1");
		WebMenu_menu5_1_1.setParentMenuId("5,1");
		WebMenu_menu5_1.getChidren().add(WebMenu_menu5_1_1);
		MenuObj WebMenu_menu5_1_1_1 = new MenuObj();
		WebMenu_menu5_1_1_1.setMenuId("5,1,1,1");
		WebMenu_menu5_1_1_1.setMenuName("编辑");
		WebMenu_menu5_1_1_1.setMenuOpName("dsjs_web_ed");
		WebMenu_menu5_1_1_1.setAction("");
		WebMenu_menu5_1_1_1.setIcon("");
		WebMenu_menu5_1_1_1.setParentMenuId("5,1,1");
		WebMenu_menu5_1_1.getChidren().add(WebMenu_menu5_1_1_1);
		MenuObj WebMenu_menu5_1_1_2 = new MenuObj();
		WebMenu_menu5_1_1_2.setMenuId("5,1,1,2");
		WebMenu_menu5_1_1_2.setMenuName("删除");
		WebMenu_menu5_1_1_2.setMenuOpName("dsjs_web_del");
		WebMenu_menu5_1_1_2.setAction("");
		WebMenu_menu5_1_1_2.setIcon("");
		WebMenu_menu5_1_1_2.setParentMenuId("5,1,1");
		WebMenu_menu5_1_1.getChidren().add(WebMenu_menu5_1_1_2);
		MenuObj WebMenu_menu5_1_2 = new MenuObj();
		WebMenu_menu5_1_2.setMenuId("5,1,2");
		WebMenu_menu5_1_2.setMenuName("对下结算");
		WebMenu_menu5_1_2.setMenuOpName("dxjs_web");
		WebMenu_menu5_1_2.setAction("../finance/balanceDownList.html");
		WebMenu_menu5_1_2.setIcon("left1");
		WebMenu_menu5_1_2.setParentMenuId("5,1");
		WebMenu_menu5_1.getChidren().add(WebMenu_menu5_1_2);
		MenuObj WebMenu_menu5_1_2_1 = new MenuObj();
		WebMenu_menu5_1_2_1.setMenuId("5,1,2,1");
		WebMenu_menu5_1_2_1.setMenuName("删除");
		WebMenu_menu5_1_2_1.setMenuOpName("dxjs_web_del");
		WebMenu_menu5_1_2_1.setAction("");
		WebMenu_menu5_1_2_1.setIcon("");
		WebMenu_menu5_1_2_1.setParentMenuId("5,1,2");
		WebMenu_menu5_1_2.getChidren().add(WebMenu_menu5_1_2_1);
		MenuObj WebMenu_menu5_2 = new MenuObj();
		WebMenu_menu5_2.setMenuId("5,2");
		WebMenu_menu5_2.setMenuName("报销");
		WebMenu_menu5_2.setMenuOpName("bx_web");
		WebMenu_menu5_2.setAction("");
		WebMenu_menu5_2.setIcon("top2");
		WebMenu_menu5_2.setParentMenuId("5");
		WebMenu_menu5.getChidren().add(WebMenu_menu5_2);
		MenuObj WebMenu_menu5_2_1 = new MenuObj();
		WebMenu_menu5_2_1.setMenuId("5,2,1");
		WebMenu_menu5_2_1.setMenuName("财务报销");
		WebMenu_menu5_2_1.setMenuOpName("cwbx_web");
		WebMenu_menu5_2_1.setAction("../finance/reimburse.html");
		WebMenu_menu5_2_1.setIcon("left1");
		WebMenu_menu5_2_1.setParentMenuId("5,2");
		WebMenu_menu5_2.getChidren().add(WebMenu_menu5_2_1);
		MenuObj WebMenu_menu5_2_1_1 = new MenuObj();
		WebMenu_menu5_2_1_1.setMenuId("5,2,1,1");
		WebMenu_menu5_2_1_1.setMenuName("删除");
		WebMenu_menu5_2_1_1.setMenuOpName("cwbx_web_del");
		WebMenu_menu5_2_1_1.setAction("");
		WebMenu_menu5_2_1_1.setIcon("");
		WebMenu_menu5_2_1_1.setParentMenuId("5,2,1");
		WebMenu_menu5_2_1.getChidren().add(WebMenu_menu5_2_1_1);
		MenuObj WebMenu_menu5_2_2 = new MenuObj();
		WebMenu_menu5_2_2.setMenuId("5,2,2");
		WebMenu_menu5_2_2.setMenuName("单据打印");
		WebMenu_menu5_2_2.setMenuOpName("djdy_web");
		WebMenu_menu5_2_2.setAction("../finance/PrintList.html");
		WebMenu_menu5_2_2.setIcon("left1");
		WebMenu_menu5_2_2.setParentMenuId("5,2");
		WebMenu_menu5_2.getChidren().add(WebMenu_menu5_2_2);
		MenuObj WebMenu_menu6 = new MenuObj();
		WebMenu_menu6.setMenuId("6");
		WebMenu_menu6.setMenuName("管理");
		WebMenu_menu6.setMenuOpName("gl_web");
		WebMenu_menu6.setAction("");
		WebMenu_menu6.setIcon("top1");
		WebMenu_menu6.setParentMenuId("0");
		WebMenu_menu6.setChidren(new ArrayList<MenuObj>());
		WebMenu_menuList.add(WebMenu_menu6);
		MenuObj WebMenu_menu6_1 = new MenuObj();
		WebMenu_menu6_1.setMenuId("6,1");
		WebMenu_menu6_1.setMenuName("工程管理");
		WebMenu_menu6_1.setMenuOpName("xmgl_web");
		WebMenu_menu6_1.setAction("../manage/engineerList.html");
		WebMenu_menu6_1.setIcon("left1");
		WebMenu_menu6_1.setParentMenuId("6");
		WebMenu_menu6.getChidren().add(WebMenu_menu6_1);
		MenuObj WebMenu_menu6_1_1 = new MenuObj();
		WebMenu_menu6_1_1.setMenuId("6,1,1");
		WebMenu_menu6_1_1.setMenuName("编辑");
		WebMenu_menu6_1_1.setMenuOpName("xmgl_web_ed");
		WebMenu_menu6_1_1.setAction("");
		WebMenu_menu6_1_1.setIcon("");
		WebMenu_menu6_1_1.setParentMenuId("6,1");
		WebMenu_menu6_1.getChidren().add(WebMenu_menu6_1_1);
		MenuObj WebMenu_menu6_2 = new MenuObj();
		WebMenu_menu6_2.setMenuId("6,2");
		WebMenu_menu6_2.setMenuName("部门管理");
		WebMenu_menu6_2.setMenuOpName("bmgl_web");
		WebMenu_menu6_2.setAction("../manage/departmentList.html");
		WebMenu_menu6_2.setIcon("left1");
		WebMenu_menu6_2.setParentMenuId("6");
		WebMenu_menu6.getChidren().add(WebMenu_menu6_2);
		MenuObj WebMenu_menu6_2_1 = new MenuObj();
		WebMenu_menu6_2_1.setMenuId("6,2,1");
		WebMenu_menu6_2_1.setMenuName("编辑");
		WebMenu_menu6_2_1.setMenuOpName("bmgl_web_ed");
		WebMenu_menu6_2_1.setAction("");
		WebMenu_menu6_2_1.setIcon("");
		WebMenu_menu6_2_1.setParentMenuId("6,2");
		WebMenu_menu6_2.getChidren().add(WebMenu_menu6_2_1);
		MenuObj WebMenu_menu6_2_2 = new MenuObj();
		WebMenu_menu6_2_2.setMenuId("6,2,2");
		WebMenu_menu6_2_2.setMenuName("删除");
		WebMenu_menu6_2_2.setMenuOpName("bmgl_web_del");
		WebMenu_menu6_2_2.setAction("");
		WebMenu_menu6_2_2.setIcon("");
		WebMenu_menu6_2_2.setParentMenuId("6,2");
		WebMenu_menu6_2.getChidren().add(WebMenu_menu6_2_2);
		MenuObj WebMenu_menu6_3 = new MenuObj();
		WebMenu_menu6_3.setMenuId("6,3");
		WebMenu_menu6_3.setMenuName("权限管理");
		WebMenu_menu6_3.setMenuOpName("qxgl_web");
		WebMenu_menu6_3.setAction("");
		WebMenu_menu6_3.setIcon("left1");
		WebMenu_menu6_3.setParentMenuId("6");
		WebMenu_menu6.getChidren().add(WebMenu_menu6_3);
		MenuObj WebMenu_menu6_3_1 = new MenuObj();
		WebMenu_menu6_3_1.setMenuId("6,3,1");
		WebMenu_menu6_3_1.setMenuName("角色管理");
		WebMenu_menu6_3_1.setMenuOpName("jsgl_web");
		WebMenu_menu6_3_1.setAction("../manage/roleList.html");
		WebMenu_menu6_3_1.setIcon("left2");
		WebMenu_menu6_3_1.setParentMenuId("6,3");
		WebMenu_menu6_3.getChidren().add(WebMenu_menu6_3_1);
		MenuObj WebMenu_menu6_3_1_1 = new MenuObj();
		WebMenu_menu6_3_1_1.setMenuId("6,3,1,1");
		WebMenu_menu6_3_1_1.setMenuName("编辑");
		WebMenu_menu6_3_1_1.setMenuOpName("jsgl_web_ed");
		WebMenu_menu6_3_1_1.setAction("");
		WebMenu_menu6_3_1_1.setIcon("");
		WebMenu_menu6_3_1_1.setParentMenuId("6,3,1");
		WebMenu_menu6_3_1.getChidren().add(WebMenu_menu6_3_1_1);
		MenuObj WebMenu_menu6_3_1_2 = new MenuObj();
		WebMenu_menu6_3_1_2.setMenuId("6,3,1,2");
		WebMenu_menu6_3_1_2.setMenuName("删除");
		WebMenu_menu6_3_1_2.setMenuOpName("jsgl_web_del");
		WebMenu_menu6_3_1_2.setAction("");
		WebMenu_menu6_3_1_2.setIcon("");
		WebMenu_menu6_3_1_2.setParentMenuId("6,3,1");
		WebMenu_menu6_3_1.getChidren().add(WebMenu_menu6_3_1_2);
		MenuObj WebMenu_menu6_3_2 = new MenuObj();
		WebMenu_menu6_3_2.setMenuId("6,3,2");
		WebMenu_menu6_3_2.setMenuName("用户管理");
		WebMenu_menu6_3_2.setMenuOpName("yhgl_web");
		WebMenu_menu6_3_2.setAction("../manage/userList.html");
		WebMenu_menu6_3_2.setIcon("left2");
		WebMenu_menu6_3_2.setParentMenuId("6,3");
		WebMenu_menu6_3.getChidren().add(WebMenu_menu6_3_2);
		MenuObj WebMenu_menu6_3_2_1 = new MenuObj();
		WebMenu_menu6_3_2_1.setMenuId("6,3,2,1");
		WebMenu_menu6_3_2_1.setMenuName("编辑");
		WebMenu_menu6_3_2_1.setMenuOpName("yhgl_web_ed");
		WebMenu_menu6_3_2_1.setAction("");
		WebMenu_menu6_3_2_1.setIcon("");
		WebMenu_menu6_3_2_1.setParentMenuId("6,3,2");
		WebMenu_menu6_3_2.getChidren().add(WebMenu_menu6_3_2_1);
		MenuObj WebMenu_menu6_3_2_2 = new MenuObj();
		WebMenu_menu6_3_2_2.setMenuId("6,3,2,2");
		WebMenu_menu6_3_2_2.setMenuName("删除");
		WebMenu_menu6_3_2_2.setMenuOpName("yhgl_web_del");
		WebMenu_menu6_3_2_2.setAction("");
		WebMenu_menu6_3_2_2.setIcon("");
		WebMenu_menu6_3_2_2.setParentMenuId("6,3,2");
		WebMenu_menu6_3_2.getChidren().add(WebMenu_menu6_3_2_2);
		MenuObj WebMenu_menu6_3_3 = new MenuObj();
		WebMenu_menu6_3_3.setMenuId("6,3,3");
		WebMenu_menu6_3_3.setMenuName("审批管理");
		WebMenu_menu6_3_3.setMenuOpName("spgl_web");
		WebMenu_menu6_3_3.setAction("../manage/auditRulesLsit.html");
		WebMenu_menu6_3_3.setIcon("left2");
		WebMenu_menu6_3_3.setParentMenuId("6,3");
		WebMenu_menu6_3.getChidren().add(WebMenu_menu6_3_3);
		MenuObj WebMenu_menu6_3_3_1 = new MenuObj();
		WebMenu_menu6_3_3_1.setMenuId("6,3,3,1");
		WebMenu_menu6_3_3_1.setMenuName("编辑");
		WebMenu_menu6_3_3_1.setMenuOpName("spgl_web_ed");
		WebMenu_menu6_3_3_1.setAction("");
		WebMenu_menu6_3_3_1.setIcon("");
		WebMenu_menu6_3_3_1.setParentMenuId("6,3,3");
		WebMenu_menu6_3_3.getChidren().add(WebMenu_menu6_3_3_1);
		MenuObj WebMenu_menu6_3_3_2 = new MenuObj();
		WebMenu_menu6_3_3_2.setMenuId("6,3,3,2");
		WebMenu_menu6_3_3_2.setMenuName("删除");
		WebMenu_menu6_3_3_2.setMenuOpName("spgl_web_del");
		WebMenu_menu6_3_3_2.setAction("");
		WebMenu_menu6_3_3_2.setIcon("");
		WebMenu_menu6_3_3_2.setParentMenuId("6,3,3");
		WebMenu_menu6_3_3.getChidren().add(WebMenu_menu6_3_3_2);
		MenuObj WebMenu_menu6_4 = new MenuObj();
		WebMenu_menu6_4.setMenuId("6,4");
		WebMenu_menu6_4.setMenuName("设备管理");
		WebMenu_menu6_4.setMenuOpName("sbgl_web");
		WebMenu_menu6_4.setAction("");
		WebMenu_menu6_4.setIcon("left1");
		WebMenu_menu6_4.setParentMenuId("6");
		WebMenu_menu6.getChidren().add(WebMenu_menu6_4);
		MenuObj WebMenu_menu6_4_1 = new MenuObj();
		WebMenu_menu6_4_1.setMenuId("6,4,1");
		WebMenu_menu6_4_1.setMenuName("设备种类管理");
		WebMenu_menu6_4_1.setMenuOpName("sbzlgl_web");
		WebMenu_menu6_4_1.setAction("../manage/machineryTypeList.html");
		WebMenu_menu6_4_1.setIcon("left2");
		WebMenu_menu6_4_1.setParentMenuId("6,4");
		WebMenu_menu6_4.getChidren().add(WebMenu_menu6_4_1);
		MenuObj WebMenu_menu6_4_1_1 = new MenuObj();
		WebMenu_menu6_4_1_1.setMenuId("6,4,1,1");
		WebMenu_menu6_4_1_1.setMenuName("编辑");
		WebMenu_menu6_4_1_1.setMenuOpName("sbzlgl_web_ed");
		WebMenu_menu6_4_1_1.setAction("");
		WebMenu_menu6_4_1_1.setIcon("");
		WebMenu_menu6_4_1_1.setParentMenuId("6,4,1");
		WebMenu_menu6_4_1.getChidren().add(WebMenu_menu6_4_1_1);
		MenuObj WebMenu_menu6_4_1_2 = new MenuObj();
		WebMenu_menu6_4_1_2.setMenuId("6,4,1,2");
		WebMenu_menu6_4_1_2.setMenuName("删除");
		WebMenu_menu6_4_1_2.setMenuOpName("sbzlgl_web_del");
		WebMenu_menu6_4_1_2.setAction("");
		WebMenu_menu6_4_1_2.setIcon("");
		WebMenu_menu6_4_1_2.setParentMenuId("6,4,1");
		WebMenu_menu6_4_1.getChidren().add(WebMenu_menu6_4_1_2);
		MenuObj WebMenu_menu6_4_2 = new MenuObj();
		WebMenu_menu6_4_2.setMenuId("6,4,2");
		WebMenu_menu6_4_2.setMenuName("设备详情管理");
		WebMenu_menu6_4_2.setMenuOpName("sbxqgl_web");
		WebMenu_menu6_4_2.setAction("../manage/machineryList.html");
		WebMenu_menu6_4_2.setIcon("left2");
		WebMenu_menu6_4_2.setParentMenuId("6,4");
		WebMenu_menu6_4.getChidren().add(WebMenu_menu6_4_2);
		MenuObj WebMenu_menu6_4_2_1 = new MenuObj();
		WebMenu_menu6_4_2_1.setMenuId("6,4,2,1");
		WebMenu_menu6_4_2_1.setMenuName("编辑");
		WebMenu_menu6_4_2_1.setMenuOpName("sbxqgl_web_ed");
		WebMenu_menu6_4_2_1.setAction("");
		WebMenu_menu6_4_2_1.setIcon("");
		WebMenu_menu6_4_2_1.setParentMenuId("6,4,2");
		WebMenu_menu6_4_2.getChidren().add(WebMenu_menu6_4_2_1);
		MenuObj WebMenu_menu6_4_2_2 = new MenuObj();
		WebMenu_menu6_4_2_2.setMenuId("6,4,2,2");
		WebMenu_menu6_4_2_2.setMenuName("删除");
		WebMenu_menu6_4_2_2.setMenuOpName("sbxqgl_web_del");
		WebMenu_menu6_4_2_2.setAction("");
		WebMenu_menu6_4_2_2.setIcon("");
		WebMenu_menu6_4_2_2.setParentMenuId("6,4,2");
		WebMenu_menu6_4_2.getChidren().add(WebMenu_menu6_4_2_2);
		MenuObj WebMenu_menu6_5 = new MenuObj();
		WebMenu_menu6_5.setMenuId("6,5");
		WebMenu_menu6_5.setMenuName("材料管理");
		WebMenu_menu6_5.setMenuOpName("wzgl_web");
		WebMenu_menu6_5.setAction("");
		WebMenu_menu6_5.setIcon("left1");
		WebMenu_menu6_5.setParentMenuId("6");
		WebMenu_menu6.getChidren().add(WebMenu_menu6_5);
		MenuObj WebMenu_menu6_5_1 = new MenuObj();
		WebMenu_menu6_5_1.setMenuId("6,5,1");
		WebMenu_menu6_5_1.setMenuName("材料科目管理");
		WebMenu_menu6_5_1.setMenuOpName("wzkmgl_web");
		WebMenu_menu6_5_1.setAction("../manage/materialBigTypeList.html");
		WebMenu_menu6_5_1.setIcon("left2");
		WebMenu_menu6_5_1.setParentMenuId("6,5");
		WebMenu_menu6_5.getChidren().add(WebMenu_menu6_5_1);
		MenuObj WebMenu_menu6_5_1_1 = new MenuObj();
		WebMenu_menu6_5_1_1.setMenuId("6,5,1,1");
		WebMenu_menu6_5_1_1.setMenuName("编辑");
		WebMenu_menu6_5_1_1.setMenuOpName("wzkmgl_web_ed");
		WebMenu_menu6_5_1_1.setAction("");
		WebMenu_menu6_5_1_1.setIcon("");
		WebMenu_menu6_5_1_1.setParentMenuId("6,5,1");
		WebMenu_menu6_5_1.getChidren().add(WebMenu_menu6_5_1_1);
		MenuObj WebMenu_menu6_5_1_2 = new MenuObj();
		WebMenu_menu6_5_1_2.setMenuId("6,5,1,2");
		WebMenu_menu6_5_1_2.setMenuName("删除");
		WebMenu_menu6_5_1_2.setMenuOpName("wzkmgl_web_del");
		WebMenu_menu6_5_1_2.setAction("");
		WebMenu_menu6_5_1_2.setIcon("");
		WebMenu_menu6_5_1_2.setParentMenuId("6,5,1");
		WebMenu_menu6_5_1.getChidren().add(WebMenu_menu6_5_1_2);
		MenuObj WebMenu_menu6_5_2 = new MenuObj();
		WebMenu_menu6_5_2.setMenuId("6,5,2");
		WebMenu_menu6_5_2.setMenuName("材料详情管理");
		WebMenu_menu6_5_2.setMenuOpName("wzxqgl_web");
		WebMenu_menu6_5_2.setAction("../manage/materialDetailList.html");
		WebMenu_menu6_5_2.setIcon("left2");
		WebMenu_menu6_5_2.setParentMenuId("6,5");
		WebMenu_menu6_5.getChidren().add(WebMenu_menu6_5_2);
		MenuObj WebMenu_menu6_5_2_1 = new MenuObj();
		WebMenu_menu6_5_2_1.setMenuId("6,5,2,1");
		WebMenu_menu6_5_2_1.setMenuName("编辑");
		WebMenu_menu6_5_2_1.setMenuOpName("wzxqgl_web_ed");
		WebMenu_menu6_5_2_1.setAction("");
		WebMenu_menu6_5_2_1.setIcon("");
		WebMenu_menu6_5_2_1.setParentMenuId("6,5,2");
		WebMenu_menu6_5_2.getChidren().add(WebMenu_menu6_5_2_1);
		MenuObj WebMenu_menu6_5_2_2 = new MenuObj();
		WebMenu_menu6_5_2_2.setMenuId("6,5,2,2");
		WebMenu_menu6_5_2_2.setMenuName("删除");
		WebMenu_menu6_5_2_2.setMenuOpName("wzxqgl_web_del");
		WebMenu_menu6_5_2_2.setAction("");
		WebMenu_menu6_5_2_2.setIcon("");
		WebMenu_menu6_5_2_2.setParentMenuId("6,5,2");
		WebMenu_menu6_5_2.getChidren().add(WebMenu_menu6_5_2_2);
		MenuObj WebMenu_menu6_5_3 = new MenuObj();
		WebMenu_menu6_5_3.setMenuId("6,5,3");
		WebMenu_menu6_5_3.setMenuName("材料导入");
		WebMenu_menu6_5_3.setMenuOpName("wzdr_web");
		WebMenu_menu6_5_3.setAction("../manage/materialImport.html");
		WebMenu_menu6_5_3.setIcon("left2");
		WebMenu_menu6_5_3.setParentMenuId("6,5");
		WebMenu_menu6_5.getChidren().add(WebMenu_menu6_5_3);
		MenuObj WebMenu_menu6_6 = new MenuObj();
		WebMenu_menu6_6.setMenuId("6,6");
		WebMenu_menu6_6.setMenuName("分包商管理");
		WebMenu_menu6_6.setMenuOpName("fbsgl_web");
		WebMenu_menu6_6.setAction("../manage/contractorList.html");
		WebMenu_menu6_6.setIcon("left1");
		WebMenu_menu6_6.setParentMenuId("6");
		WebMenu_menu6.getChidren().add(WebMenu_menu6_6);
		MenuObj WebMenu_menu6_6_1 = new MenuObj();
		WebMenu_menu6_6_1.setMenuId("6,6,1");
		WebMenu_menu6_6_1.setMenuName("编辑");
		WebMenu_menu6_6_1.setMenuOpName("fbsgl_web_ed");
		WebMenu_menu6_6_1.setAction("");
		WebMenu_menu6_6_1.setIcon("");
		WebMenu_menu6_6_1.setParentMenuId("6,6");
		WebMenu_menu6_6.getChidren().add(WebMenu_menu6_6_1);
		MenuObj WebMenu_menu6_6_2 = new MenuObj();
		WebMenu_menu6_6_2.setMenuId("6,6,2");
		WebMenu_menu6_6_2.setMenuName("删除");
		WebMenu_menu6_6_2.setMenuOpName("fbsgl_web_del");
		WebMenu_menu6_6_2.setAction("");
		WebMenu_menu6_6_2.setIcon("");
		WebMenu_menu6_6_2.setParentMenuId("6,6");
		WebMenu_menu6_6.getChidren().add(WebMenu_menu6_6_2);
		MenuObj WebMenu_menu6_7 = new MenuObj();
		WebMenu_menu6_7.setMenuId("6,7");
		WebMenu_menu6_7.setMenuName("工种管理");
		WebMenu_menu6_7.setMenuOpName("gzgl_web");
		WebMenu_menu6_7.setAction("../manage/workTypeList.html");
		WebMenu_menu6_7.setIcon("left1");
		WebMenu_menu6_7.setParentMenuId("6");
		WebMenu_menu6.getChidren().add(WebMenu_menu6_7);
		MenuObj WebMenu_menu6_7_1 = new MenuObj();
		WebMenu_menu6_7_1.setMenuId("6,7,1");
		WebMenu_menu6_7_1.setMenuName("编辑");
		WebMenu_menu6_7_1.setMenuOpName("gzgl_web_ed");
		WebMenu_menu6_7_1.setAction("");
		WebMenu_menu6_7_1.setIcon("");
		WebMenu_menu6_7_1.setParentMenuId("6,7");
		WebMenu_menu6_7.getChidren().add(WebMenu_menu6_7_1);
		MenuObj WebMenu_menu6_7_2 = new MenuObj();
		WebMenu_menu6_7_2.setMenuId("6,7,2");
		WebMenu_menu6_7_2.setMenuName("删除");
		WebMenu_menu6_7_2.setMenuOpName("gzgl_web_del");
		WebMenu_menu6_7_2.setAction("");
		WebMenu_menu6_7_2.setIcon("");
		WebMenu_menu6_7_2.setParentMenuId("6,7");
		WebMenu_menu6_7.getChidren().add(WebMenu_menu6_7_2);
		MenuObj WebMenu_menu6_8 = new MenuObj();
		WebMenu_menu6_8.setMenuId("6,8");
		WebMenu_menu6_8.setMenuName("管理费用上缴公式");
		WebMenu_menu6_8.setMenuOpName("glfysjgs_web");
		WebMenu_menu6_8.setAction("../manage/manageRatioList.html");
		WebMenu_menu6_8.setIcon("left1");
		WebMenu_menu6_8.setParentMenuId("6");
		WebMenu_menu6.getChidren().add(WebMenu_menu6_8);
		MenuObj WebMenu_menu6_8_1 = new MenuObj();
		WebMenu_menu6_8_1.setMenuId("6,8,1");
		WebMenu_menu6_8_1.setMenuName("编辑");
		WebMenu_menu6_8_1.setMenuOpName("glfysjgs_web_ed");
		WebMenu_menu6_8_1.setAction("");
		WebMenu_menu6_8_1.setIcon("");
		WebMenu_menu6_8_1.setParentMenuId("6,8");
		WebMenu_menu6_8.getChidren().add(WebMenu_menu6_8_1);
		MenuObj WebMenu_menu6_9 = new MenuObj();
		WebMenu_menu6_9.setMenuId("6,9");
		WebMenu_menu6_9.setMenuName("合同管理");
		WebMenu_menu6_9.setMenuOpName("htgl_web");
		WebMenu_menu6_9.setAction("../manage/contracttList.html");
		WebMenu_menu6_9.setIcon("left1");
		WebMenu_menu6_9.setParentMenuId("6");
		WebMenu_menu6.getChidren().add(WebMenu_menu6_9);
		MenuObj WebMenu_menu6_9_1 = new MenuObj();
		WebMenu_menu6_9_1.setMenuId("6,9,1");
		WebMenu_menu6_9_1.setMenuName("编辑");
		WebMenu_menu6_9_1.setMenuOpName("htgl_web_ed");
		WebMenu_menu6_9_1.setAction("");
		WebMenu_menu6_9_1.setIcon("");
		WebMenu_menu6_9_1.setParentMenuId("6,9");
		WebMenu_menu6_9.getChidren().add(WebMenu_menu6_9_1);
		MenuObj WebMenu_menu6_9_2 = new MenuObj();
		WebMenu_menu6_9_2.setMenuId("6,9,2");
		WebMenu_menu6_9_2.setMenuName("删除");
		WebMenu_menu6_9_2.setMenuOpName("htgl_web_del");
		WebMenu_menu6_9_2.setAction("");
		WebMenu_menu6_9_2.setIcon("");
		WebMenu_menu6_9_2.setParentMenuId("6,9");
		WebMenu_menu6_9.getChidren().add(WebMenu_menu6_9_2);
		MenuObj WebMenu_menu6_10 = new MenuObj();
		WebMenu_menu6_10.setMenuId("6,10");
		WebMenu_menu6_10.setMenuName("通讯录管理");
		WebMenu_menu6_10.setMenuOpName("txlgl_web");
		WebMenu_menu6_10.setAction("");
		WebMenu_menu6_10.setIcon("left1");
		WebMenu_menu6_10.setParentMenuId("6");
		WebMenu_menu6.getChidren().add(WebMenu_menu6_10);
		MenuObj WebMenu_menu6_10_1 = new MenuObj();
		WebMenu_menu6_10_1.setMenuId("6,10,1");
		WebMenu_menu6_10_1.setMenuName("通讯录导入");
		WebMenu_menu6_10_1.setMenuOpName("txldr_web");
		WebMenu_menu6_10_1.setAction("../manage/phoneListImport.html");
		WebMenu_menu6_10_1.setIcon("left2");
		WebMenu_menu6_10_1.setParentMenuId("6,10");
		WebMenu_menu6_10.getChidren().add(WebMenu_menu6_10_1);
		MenuObj WebMenu_menu6_10_2 = new MenuObj();
		WebMenu_menu6_10_2.setMenuId("6,10,2");
		WebMenu_menu6_10_2.setMenuName("通讯录列表");
		WebMenu_menu6_10_2.setMenuOpName("txllb_web");
		WebMenu_menu6_10_2.setAction("../manage/phoneList.html");
		WebMenu_menu6_10_2.setIcon("left2");
		WebMenu_menu6_10_2.setParentMenuId("6,10");
		WebMenu_menu6_10.getChidren().add(WebMenu_menu6_10_2);
		MenuObj WebMenu_menu6_10_2_1 = new MenuObj();
		WebMenu_menu6_10_2_1.setMenuId("6,10,2,1");
		WebMenu_menu6_10_2_1.setMenuName("编辑");
		WebMenu_menu6_10_2_1.setMenuOpName("txllb_web_ed");
		WebMenu_menu6_10_2_1.setAction("");
		WebMenu_menu6_10_2_1.setIcon("");
		WebMenu_menu6_10_2_1.setParentMenuId("6,10,2");
		WebMenu_menu6_10_2.getChidren().add(WebMenu_menu6_10_2_1);
		MenuObj WebMenu_menu6_10_2_2 = new MenuObj();
		WebMenu_menu6_10_2_2.setMenuId("6,10,2,2");
		WebMenu_menu6_10_2_2.setMenuName("删除");
		WebMenu_menu6_10_2_2.setMenuOpName("txllb_web_del");
		WebMenu_menu6_10_2_2.setAction("");
		WebMenu_menu6_10_2_2.setIcon("");
		WebMenu_menu6_10_2_2.setParentMenuId("6,10,2");
		WebMenu_menu6_10_2.getChidren().add(WebMenu_menu6_10_2_2);
		MenuObj WebMenu_menu6_11 = new MenuObj();
		WebMenu_menu6_11.setMenuId("6,11");
		WebMenu_menu6_11.setMenuName("版本管理");
		WebMenu_menu6_11.setMenuOpName("bbgl_web");
		WebMenu_menu6_11.setAction("../manage/updateOpt.html");
		WebMenu_menu6_11.setIcon("left1");
		WebMenu_menu6_11.setParentMenuId("6");
		WebMenu_menu6.getChidren().add(WebMenu_menu6_11);
	}
}
